using System.Numerics;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
namespace Content.Client._DV.UserInterfaces.Controls;

[GenerateTypedNameReferences]
public sealed partial class AdvancedProgressBar : Control
{
    public const string BackgroundStyleClass = "Background";
    public const string ForegroundStyleClass = "Foreground";
    public const string ColorableStyleClass = "Colorable";
    
    public enum BarOrientation : byte
    {
        RightToLeft,
        LeftToRight,
        TopToBottom,
        BottomToTop
    }
    
    [PublicAPI]
    public BarOrientation Orientation
    {
        get;
        set
        {
            field = value;
            BindValues();
        }
    } = BarOrientation.LeftToRight;
    
    [PublicAPI]
    public int MinimumValue
    {
        get;
        set
        {
            field = value;
            BindValues();
        }
    } = 0;

    [PublicAPI]
    public int MaximumValue
    {
        get;
        set
        {
            field = value;
            BindValues();
        }
    } = 100;

    [PublicAPI]
    public int Value
    {
        get;
        set
        {
            field = Math.Clamp(value, MinimumValue, MaximumValue);
            BindValues();
        }
    } = 0;
    
    [PublicAPI]
    public float Percent => MaximumValue == 0 ? 0 : (float) Value / MaximumValue;

    [PublicAPI]
    public Color? ForegroundColor
    {
        get => Foreground.ModulateSelfOverride;
        set => Foreground.ModulateSelfOverride = value;
    }
    
    [PublicAPI]
    public Color? BackgroundColor
    {
        get => Background.ModulateSelfOverride;
        set => Background.ModulateSelfOverride = value;
    }

    [PublicAPI]
    public Thickness InsideMargin
    {
        get => Foreground.Margin;
        set => Foreground.Margin = value;
    }

    public AdvancedProgressBar()
    {
        RobustXamlLoader.Load(this);
    }
    
    protected override Vector2 MeasureOverride(Vector2 availableSize)
    {
        return Vector2.Zero;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        switch (Orientation)
        {
            default:
            case BarOrientation.LeftToRight:
            case BarOrientation.RightToLeft:
                Foreground.SetWidth = (Width - InsideMargin.SumHorizontal) * Percent;
                Foreground.SetHeight = float.NaN;
                break;
            
            case BarOrientation.TopToBottom:
            case BarOrientation.BottomToTop:
                Foreground.SetWidth = float.NaN;
                Foreground.SetHeight = (Height - InsideMargin.SumVertical) * Percent;
                break;
        }
        
        base.Draw(handle);
    }

    private void BindValues()
    {
        Background.SetOnlyStyleClass(BackgroundColor.HasValue ? ColorableStyleClass : BackgroundStyleClass);
        Foreground.SetOnlyStyleClass(ForegroundColor.HasValue ? ColorableStyleClass : ForegroundStyleClass);

        switch (Orientation)
        {
            default:
            case BarOrientation.LeftToRight:
            case BarOrientation.RightToLeft:
                Foreground.HorizontalAlignment = Orientation == BarOrientation.RightToLeft ? HAlignment.Right : HAlignment.Left;
                Foreground.VerticalAlignment = VAlignment.Stretch;
                break;
            
            case BarOrientation.TopToBottom:
            case BarOrientation.BottomToTop:
                Foreground.HorizontalAlignment = HAlignment.Stretch;
                Foreground.VerticalAlignment = Orientation == BarOrientation.BottomToTop ? VAlignment.Bottom : VAlignment.Top;
                break;
        }
    }
}
