using System.Numerics;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
namespace Content.Client._DV.UserInterfaces.Controls;

[GenerateTypedNameReferences]
public sealed partial class AdvancedProgressBar : Control
{
    /// <summary>
    ///     Style Class for targeting this control's Background <see cref="PanelContainer"/>
    /// </summary>
    [PublicAPI]
    public const string StyleClassBackgroundPanelContainer = "BackgroundPanelContainer";
    
    /// <summary>
    ///     Style class for targeting this control's Foreground <see cref="PanelContainer"/>
    /// </summary>
    [PublicAPI]
    public const string StyleClassForegroundPanelContainer = "ForegroundPanelContainer";
    
    /// <summary>
    ///     Style Property for setting the background color of the progress bar.
    /// </summary>
    [PublicAPI]
    public const string StylePropertyBackgroundColor = "Modulate:Background";
    
    /// <summary>
    ///     Style Property for setting the foreground color of the progress bar.
    /// </summary>
    [PublicAPI]
    public const string StylePropertyForegroundColor = "Modulate:Foreground";
    
    /// <summary>
    ///    Style Pseudo Class for the current orientation of the progress bar.
    /// </summary>
    [PublicAPI]
    public const string StylePseudoClassLeftToRight = ":LeftToRight";
    
    /// <summary>
    ///    Style Pseudo Class for the current orientation of the progress bar.
    /// </summary>
    [PublicAPI]
    public const string StylePseudoClassRightToLeft = ":RightToLeft";
    
    /// <summary>
    ///     Style Pseudo Class for the current orientation of the progress bar.
    /// </summary>
    [PublicAPI]
    public const string StylePseudoClassTopToBottom = ":TopToBottom";
    
    /// <summary>
    ///    Style Pseudo Class for the current orientation of the progress bar.
    /// </summary>
    [PublicAPI]
    public const string StylePseudoClassBottomToTop = ":BottomToTop";
    
    /// <summary>
    ///    Style Pseudo Class for when the progress bar's value is at its minimum.
    /// </summary>
    [PublicAPI]
    public const string StylePseudoClassEmpty = ":Empty";
    
    /// <summary>
    ///    Style Pseudo Class for when the progress bar's value is at its maximum.
    /// </summary>
    [PublicAPI]
    public const string StylePseudoClassFull = ":Full";
    
    /// <summary>
    ///    Style Pseudo Class for when the progress bar's percentage is in the range of [1%, 25%).
    /// </summary>
    [PublicAPI]
    public const string StylePseudoClassFirstQuartile = ":FirstQuartile";
    
    /// <summary>
    ///     Style Pseudo Class for when the progress bar's percentage is in the range of [25%, 50%).
    /// </summary>
    [PublicAPI]
    public const string StylePseudoClassSecondQuartile = ":SecondQuartile";
    
    /// <summary>
    ///     Style Pseudo Class for when the progress bar's percentage is in the range of [50%, 75%).
    /// </summary>
    [PublicAPI]
    public const string StylePseudoClassThirdQuartile = ":ThirdQuartile";
    
    /// <summary>
    ///     Style Pseudo Class for when the progress bar's percentage is in the range of [75%, 100%).
    /// </summary>
    [PublicAPI]
    public const string StylePseudoClassFourthQuartile = ":FourthQuartile";
    
    public enum BarOrientation : byte
    {
        RightToLeft,
        LeftToRight,
        TopToBottom,
        BottomToTop
    }
    
    [PublicAPI]
    public BarOrientation Orientation
    {
        get;
        set
        {
            if (field == value) return;
            
            field = value;
            UpdateStylePseudoClasses();
        }
    } = BarOrientation.LeftToRight;
    
    [PublicAPI]
    public int MinimumValue
    {
        get;
        set
        {
            if (field == value) return;
            
            field = value;
            UpdateStylePseudoClasses();
        }
    } = 0;

    [PublicAPI]
    public int MaximumValue
    {
        get;
        set
        {
            if (field == value) return;
            
            field = value;
            UpdateStylePseudoClasses();
        }
    } = 100;

    [PublicAPI]
    public int Value
    {
        get;
        set
        {
            if (field == value) return;
            
            field = value;
            UpdateStylePseudoClasses();
        }
    } = 0;
    
    [PublicAPI]
    public float Percent => MaximumValue == 0 ? 0 : (float) (Value - MinimumValue) / MaximumValue;

    [PublicAPI]
    public Color? ForegroundColorOverride
    {
        get;
        set
        {
            if (field == value) return;
            
            field = value;
            InvalidateStyleSheet();
        }
    }
    
    [PublicAPI]
    public Color? BackgroundColorOverride
    {
        get;
        set
        {
            if (field == value) return;
            
            field = value;
            InvalidateStyleSheet();
        }
    }

    [PublicAPI]
    public Thickness InsideMargin
    {
        get => Foreground.Margin;
        set => Foreground.Margin = value;
    }

    public AdvancedProgressBar()
    {
        RobustXamlLoader.Load(this);
        
        UpdateStylePseudoClasses();
    }

    protected override void StylePropertiesChanged()
    {
        Foreground.ModulateSelfOverride = GetActualForegroundColor();
        Background.ModulateSelfOverride = GetActualBackgroundColor();
        
        base.StylePropertiesChanged();
    }
    
    protected override Vector2 MeasureOverride(Vector2 availableSize)
    {
        // Returning zero here makes it so we can reliably use this control's width/height to scale the size of the "bar"
        return Vector2.Zero;
    }
    
    protected override void FrameUpdate(FrameEventArgs args)
    {
        switch (Orientation)
        {
            default:
            case BarOrientation.LeftToRight:
            case BarOrientation.RightToLeft:
                Foreground.SetWidth = (Width - InsideMargin.SumHorizontal) * Percent;
                Foreground.SetHeight = float.NaN;
                break;
            
            case BarOrientation.TopToBottom:
            case BarOrientation.BottomToTop:
                Foreground.SetWidth = float.NaN;
                Foreground.SetHeight = (Height - InsideMargin.SumVertical) * Percent;
                break;
        }

        base.FrameUpdate(args);
    }
    
    private void UpdateStylePseudoClasses()
    {
        var pseudo = Orientation switch
        {
            BarOrientation.LeftToRight => StylePseudoClassLeftToRight,
            BarOrientation.RightToLeft => StylePseudoClassRightToLeft,
            BarOrientation.TopToBottom => StylePseudoClassTopToBottom,
            BarOrientation.BottomToTop => StylePseudoClassBottomToTop,
            _ => throw new ArgumentOutOfRangeException()
        };
        
        SetOnlyStylePseudoClass(pseudo);

        Value = Math.Clamp(Value, MinimumValue, MaximumValue);
        
        if (Value == MinimumValue)
        {
            AddStylePseudoClass(StylePseudoClassEmpty);
        }
        else if (Value == MaximumValue)
        {
            AddStylePseudoClass(StylePseudoClassFull);
        }
        else
        {
            switch (Percent)
            {
                case < 0.25f:
                    AddStylePseudoClass(StylePseudoClassFirstQuartile);
                    break;
                case < 0.5f:
                    AddStylePseudoClass(StylePseudoClassSecondQuartile);
                    break;
                case < 0.75f:
                    AddStylePseudoClass(StylePseudoClassThirdQuartile);
                    break;
                default:
                    AddStylePseudoClass(StylePseudoClassFourthQuartile);
                    break;
            }
        }
        
        InvalidateStyleSheet();
    }
    
    private Color? GetActualBackgroundColor()
    {
        if (BackgroundColorOverride is not null) return BackgroundColorOverride.Value;
        
        if (TryGetStyleProperty<Color>(StylePropertyBackgroundColor, out var backgroundColor)) return backgroundColor;
        
        return null;
    }

    private Color? GetActualForegroundColor()
    {
        if (ForegroundColorOverride is not null) return ForegroundColorOverride.Value;

        if (TryGetStyleProperty<Color>(StylePropertyForegroundColor, out var foregroundColor)) return foregroundColor;

        return null;
    }
}
