using JetBrains.Annotations;
using Robust.Client.Animations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DV.UserInterfaces.Controls;

[GenerateTypedNameReferences]
public sealed partial class StatusLight : Control
{
    private const string BlinkingAnimationKey = "Blinking";

    /// <summary>
    ///     Style Class for the Status Light which sets the blinking animation to On 100ms, Off 100ms
    /// </summary>
    [PublicAPI]
    public const string StyleClassFastBlinking = "BlinkingAnimation:Fast";

    /// <summary>
    ///     Style Class for the Status Light which sets the blinking animation to On 400ms, Off 400ms
    /// </summary>
    [PublicAPI]
    public const string StyleClassSlowBlinking = "BlinkingAnimation:Slow";

    /// <summary>
    ///     Style Class for targeting this control's Active Light <see cref="TextureRect"/>.
    /// </summary>
    [PublicAPI]
    public const string StyleClassActiveLight = "StatusLight.ActiveLight";

    /// <summary>
    ///     Style Class for targeting this control's Base Light <see cref="TextureRect"/>.
    /// </summary>
    [PublicAPI]
    public const string StyleClassBaseLight = "StatusLight.BaseLight";

    /// <summary>
    ///     Style Pseudo Class for when the light is on. This is mutually exclusive with <see cref="StylePseudoClassIsOff"/>.
    /// </summary>
    [PublicAPI]
    public const string StylePseudoClassIsOn = ":IsOn";

    /// <summary>
    ///     Style Pseudo Class for when the light is off. This is mutually exclusive with <see cref="StylePseudoClassIsOn"/>.
    /// </summary>
    [PublicAPI]
    public const string StylePseudoClassIsOff = ":IsOff";

    /// <summary>
    ///     Style Property for setting the blinking animation.
    /// </summary>
    [PublicAPI]
    public const string StylePropertyBlinkingAnimation = "Animation:Blinking";

    /// <summary>
    ///     Style Property for setting the active color of the light. This is the color shown when the light is on.
    /// </summary>
    [PublicAPI]
    public const string StylePropertyActiveColor = "Modulate:Light";

    /// <summary>
    ///     Style Property for setting the base color of the light. This is the color shown when the light is off.
    /// </summary>
    [PublicAPI]
    public const string StylePropertyBaseColor = "Modulate:Base";

    /// <summary>
    ///     Whether the indicator should be lit.
    /// </summary>
    [PublicAPI]
    public bool IsOn
    {
        get;
        set
        {
            if (field == value) return;

            field = value;
            UpdateStylePseudoClasses();
        }
    }

    /// <summary>
    ///     The color of the indicator when it is on.
    /// </summary>
    [PublicAPI]
    public Color? ActiveColorOverride
    {
        get;
        set
        {
            if (field == value) return;

            field = value;
            InvalidateStyleSheet();
        }
    }

    /// <summary>
    ///     The base color of the indicator, also shown when it is off.
    /// </summary>
    [PublicAPI]
    public Color? BaseColorOverride
    {
        get;
        set
        {
            if (field == value) return;

            field = value;
            InvalidateStyleSheet();
        }
    }

    /// <summary>
    ///     The <see cref="Texture"/> used by the Active Light.
    /// </summary>
    [PublicAPI]
    public Texture? ActiveLightTextureOverride
    {
        get => ActiveLight.Texture;
        set => ActiveLight.Texture = value;
    }

    /// <summary>
    ///     The <see cref="Texture"/> used by the Base Light.
    /// </summary>
    [PublicAPI]
    public Texture? BaseLightTextureOverride
    {
        get => BaseLight.Texture;
        set => BaseLight.Texture = value;
    }

    /// <summary>
    ///     The blinking animation to use for the Active Light.
    /// </summary>
    [PublicAPI]
    public Animation? BlinkingAnimationOverride
    {
        get;
        set
        {
            if (field == value) return;

            field = value;
            InvalidateStyleSheet();
        }
    }

    public StatusLight()
    {
        RobustXamlLoader.Load(this);
        UpdateStylePseudoClasses();
        ActiveLight.AnimationCompleted += ActiveLightOnAnimationCompleted;
    }

    protected override void StylePropertiesChanged()
    {
        if (GetActualBaseColor() is var baseColor) BaseLight.ModulateSelfOverride = baseColor;

        if (GetActualActiveColor() is var activeColor) ActiveLight.ModulateSelfOverride = activeColor;

        SetActiveLightAnimation();

        base.StylePropertiesChanged();
    }

    private void UpdateStylePseudoClasses()
    {
        SetOnlyStylePseudoClass(IsOn ? StylePseudoClassIsOn : StylePseudoClassIsOff);
        ActiveLight.Visible = IsOn;

        InvalidateStyleSheet();
    }

    /// <summary>
    ///     Reset the blinking animation based on the current style and overrides. If there is no blinking animation, stop any currently playing animation.
    /// </summary>
    private void SetActiveLightAnimation()
    {
        if (GetActualBlinkingAnimation() is not { } blinkingAnimation)
        {
            ActiveLight.StopAnimation(BlinkingAnimationKey);
        }
        else if (!ActiveLight.HasRunningAnimation(BlinkingAnimationKey))
        {
            ActiveLight.PlayAnimation(blinkingAnimation, BlinkingAnimationKey);
        }
    }

    /// <summary>
    ///     Handler for the AnimationCompleted delegate.
    /// </summary>
    /// <param name="animationId"></param>
    private void ActiveLightOnAnimationCompleted(string animationId)
    {
        SetActiveLightAnimation();
    }

    private Animation? GetActualBlinkingAnimation()
    {
        if (BlinkingAnimationOverride is not null) return BlinkingAnimationOverride;

        if (TryGetStyleProperty<Animation>(StylePropertyBlinkingAnimation, out var blinkingAnimation)) return blinkingAnimation;

        return null;
    }

    private Color GetActualActiveColor()
    {
        if (ActiveColorOverride is not null) return ActiveColorOverride.Value;

        if (TryGetStyleProperty<Color>(StylePropertyActiveColor, out var activeColor)) return activeColor;

        return Color.White;
    }

    private Color GetActualBaseColor()
    {
        if (BaseColorOverride is not null) return BaseColorOverride.Value;

        if (TryGetStyleProperty<Color>(StylePropertyBaseColor, out var baseColor)) return baseColor;

        return Color.White;
    }
}
