using JetBrains.Annotations;
using Robust.Client.Animations;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Animations;

namespace Content.Client._DV.UserInterfaces.Controls;

[GenerateTypedNameReferences]
public sealed partial class StatusLight : Control
{
    private const string BlinkingAnimationKey = "blink";
    
    private static readonly Color DefaultDimColor = Color.FromHex("#202020");
    
    private static readonly Animation BlinkingFastAnimation = new()
    {
        Length = TimeSpan.FromSeconds(0.2),
        AnimationTracks =
        {
            new AnimationTrackControlProperty
            {
                Property = nameof(Modulate),
                InterpolationMode = AnimationInterpolationMode.Linear,
                KeyFrames =
                {
                    new AnimationTrackProperty.KeyFrame(Color.White, 0f),
                    new AnimationTrackProperty.KeyFrame(Color.Transparent, 0.1f),
                    new AnimationTrackProperty.KeyFrame(Color.White, 0.1f)
                }
            }
        }
    };

    private static readonly Animation BlinkingSlowAnimation = new()
    {
        Length = TimeSpan.FromSeconds(0.8),
        AnimationTracks =
        {
            new AnimationTrackControlProperty
            {
                Property = nameof(Modulate),
                InterpolationMode = AnimationInterpolationMode.Linear,
                KeyFrames =
                {
                    new AnimationTrackProperty.KeyFrame(Color.White, 0f),
                    new AnimationTrackProperty.KeyFrame(Color.White, 0.3f),
                    new AnimationTrackProperty.KeyFrame(Color.Transparent, 0.1f),
                    new AnimationTrackProperty.KeyFrame(Color.Transparent, 0.3f),
                    new AnimationTrackProperty.KeyFrame(Color.White, 0.1f),
                }
            }
        }
    };
    
    public enum BlinkMode : byte
    {
        /// <summary>
        ///     Blinking disabled. 
        /// </summary>
        None,
        
        /// <summary>
        ///     Blink once per 200ms.
        /// </summary>
        Fast,
        
        /// <summary>
        ///     Blink once per 800ms.
        /// </summary>
        Slow
    }

    /// <summary>
    ///     The blinking mode of the indicator, if any. Defaults to <see cref="BlinkMode.None"/>.
    /// </summary>
    [PublicAPI]
    public BlinkMode Blinking
    {
        get;
        set
        {
            if (field == value) return;
            
            field = value;
            BindValues();
        }
    } = BlinkMode.None;
    
    /// <summary>
    ///     Whether the indicator should be lit.
    /// </summary>
    [PublicAPI]
    public bool IsOn
    {
        get;
        set
        {
            if (field == value) return;

            field = value;
            BindValues();
        }
    }

    /// <summary>
    ///     The color of the indicator when it is on.
    /// </summary>
    [PublicAPI]
    public Color Color
    {
        get;
        set
        {
            if (field == value) return;

            field = value;
            BindValues();
        }
    } = Color.Green.WithAlpha(0.33f);

    /// <summary>
    ///     The base color of the indicator, also shown when it is off.
    /// </summary>
    [PublicAPI]
    public Color? DimColor
    {
        get;
        set
        {
            if (field == value) return;

            field = value;
            BindValues();
        }
    }

    /// <summary>
    ///     The <see cref="Texture"/> used by the Active Light.
    /// </summary>
    [PublicAPI]
    public Texture? ActiveLightTexture
    {
        get => ActiveLight.Texture;
        set => ActiveLight.Texture = value;
    }
    
    /// <summary>
    ///     Setter to load a <see cref="Texture"/> into <see cref="ActiveLightTexture"/>.
    /// </summary>
    /// <remarks>
    ///     Shortcut for the <see cref="TextureRect.TexturePath"/> property.
    /// </remarks>
    [PublicAPI]
    public string ActiveLightTexturePath
    {
        set => ActiveLight.TexturePath = value;
    }
    
    /// <summary>
    ///     The <see cref="Texture"/> used by the Base Light.
    /// </summary>
    [PublicAPI]
    public Texture? BaseLightTexture
    {
        get => BaseLight.Texture;
        set => BaseLight.Texture = value;
    }

    /// <summary>
    ///     Setter to load a <see cref="Texture"/> into <see cref="BaseLightTexture"/>.
    /// </summary>
    /// <remarks>
    ///     Shortcut for the <see cref="TextureRect.TexturePath"/> property.
    /// </remarks>
    [PublicAPI]
    public string BaseLightTexturePath
    {
        set => BaseLight.TexturePath = value;
    }

    public StatusLight()
    {
        RobustXamlLoader.Load(this);
        
        ActiveLight.AnimationCompleted += OnAnimationCompleted;
        
        BindValues();
    }

    /// <summary>
    ///     Update the control's visuals based on the current property values.
    /// </summary>
    private void BindValues()
    {
        BaseLight.ModulateSelfOverride = DimColor ?? DefaultDimColor;
        ActiveLight.ModulateSelfOverride = Color;
        ActiveLight.Visible = IsOn;
        
        ResetAnimation();
    }

    /// <summary>
    ///     Reset the blinking animation based on the current <see cref="Blinking"/> mode.
    /// </summary>
    private void ResetAnimation()
    {
        if (!IsOn)
        {
            ActiveLight.StopAnimation(BlinkingAnimationKey);
        }
        else
        {
            switch (Blinking)
            {
                case BlinkMode.Fast:
                    ActiveLight.PlayAnimation(BlinkingFastAnimation, BlinkingAnimationKey);
                    break;
                case BlinkMode.Slow:
                    ActiveLight.PlayAnimation(BlinkingSlowAnimation, BlinkingAnimationKey);
                    break;
                case BlinkMode.None:
                    ActiveLight.StopAnimation(BlinkingAnimationKey);
                    break;
                default:
                    throw new InvalidOperationException($"Unhandled {nameof(BlinkMode)}: {Blinking}");
            }
        }
    }

    /// <summary>
    ///     Handler for the AnimationCompleted delegate.
    /// </summary>
    /// <param name="animationId"></param>
    private void OnAnimationCompleted(string animationId)
    {
        if(animationId != BlinkingAnimationKey) return;
        
        ResetAnimation();
    }
}
