using System.Numerics;
using Content.Client._DV.Kitchen.UI.Controls;
using Content.Shared._DV.Kitchen.Components;
using Content.Shared._DV.Kitchen.Systems;
using Content.Shared.FixedPoint;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._DV.Kitchen.UI;

[GenerateTypedNameReferences]
public sealed partial class DeepFryerWindow : BaseWindow
{
    private const int DragMarginSize = 7;

    [Dependency]
    private readonly IEntityManager _entityManager = default!;

    private readonly SharedDeepFryerSystem _deepFryer;

    private FormattedMessage? _oilQualityTooltip;

    /// <summary>
    ///     Event raised when pressing a <see cref="FryerItemButton"/> with an assigned <see cref="FryerItemButton.ItemEntity"/>.
    /// </summary>
    [PublicAPI]
    public event Action<EntityUid>? OnFoodItemPressed;

    /// <summary>
    ///     Event raised when pressing a <see cref="FryerItemButton"/> without an assigned <see cref="FryerItemButton.ItemEntity"/>.
    /// </summary>
    [PublicAPI]
    public event Action? OnEmptyItemPressed;

    /// <summary>
    ///     The quality value of the oil.
    /// </summary>
    [PublicAPI]
    public float OilQuality
    {
        get;
        set
        {
            if (MathHelper.CloseTo(field, value))
                return;

            field = value;
            BindValues();
        }
    } = 1.0f;

    /// <summary>
    ///     The minimum volume of the deep fryer's oil solution to allow cooking.
    /// </summary>
    [PublicAPI]
    public FixedPoint2 MinimumVolume
    {
        get;
        set
        {
            if (field == value)
                return;

            field = value;
            BindValues();
        }
    }

    /// <summary>
    ///     The current color of the deep fryer's oil solution.
    /// </summary>
    [PublicAPI]
    public Color SolutionColor
    {
        get;
        set
        {
            if (field == value)
                return;

            field = value;
            BindValues();
        }
    } = Color.Yellow;

    /// <summary>
    ///     The current volume of the deep fryer's oil solution.
    /// </summary>
    [PublicAPI]
    public FixedPoint2 SolutionVolume
    {
        get;
        set
        {
            if (field == value)
                return;

            field = value;
            BindValues();
        }
    }

    /// <summary>
    ///     The maximum volume of the deep fryer's oil solution.
    /// </summary>
    [PublicAPI]
    public FixedPoint2 SolutionMaxVolume
    {
        get;
        set
        {
            if (field == value)
                return;

            field = value;
            BindValues();
        }

    }

    /// <summary>
    ///     The maximum number of items that can be inside the deep fryer.
    /// </summary>
    [PublicAPI]
    public int Capacity
    {
        get;
        set
        {
            if (field == value)
                return;

            field = value;
            BindValues();
        }
    } = 3;

    /// <summary>
    ///     Whether the deep fryer is powered or not.
    /// </summary>
    [PublicAPI]
    public bool IsPowered
    {
        get;
        set
        {
            field = value;
            BindValues();
        }
    }

    /// <summary>
    ///     The entities contained in the deep fryer.
    /// </summary>
    [PublicAPI]
    public IReadOnlyList<EntityUid> CookingItems { get; set; } = [];

    /// <summary>
    ///     The <see cref="OilQuality"/> level of the oil, as determined by <see cref="SharedDeepFryerSystem"/>.
    /// </summary>
    private OilQuality OilQualityCategory => SharedDeepFryerSystem.GetOilQualityLevel(OilQuality);

    public DeepFryerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _deepFryer = _entityManager.System<SharedDeepFryerSystem>();

        BasketControl.TooltipSupplier = BuildOilQualityTooltip;

        CloseButton.OnPressed += _ => Close();
        FryerBaskets.OnEmptyItemPressed += () => OnEmptyItemPressed?.Invoke();
        FryerBaskets.OnFoodItemPressed += entity => OnFoodItemPressed?.Invoke(entity);

        BindValues();
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        var mode = DragMode.Move;

        if (Resizable)
        {
            if (relativeMousePos.Y < DragMarginSize)
            {
                mode = DragMode.Top;
            }
            else if (relativeMousePos.Y > Size.Y - DragMarginSize)
            {
                mode = DragMode.Bottom;
            }

            if (relativeMousePos.X < DragMarginSize)
            {
                mode |= DragMode.Left;
            }
            else if (relativeMousePos.X > Size.X - DragMarginSize)
            {
                mode |= DragMode.Right;
            }
        }

        return mode;
    }

    private (Color color, string labelName) GetOilQualityInfo() => _deepFryer.GetOilQualityInfo(OilQualityCategory);

    private Tooltip? BuildOilQualityTooltip(Control control)
    {
        if (SolutionVolume.Value == 0 || _oilQualityTooltip is null) return null;

        var tooltip = new Tooltip
        {
            Tracking = true
        };

        tooltip.SetMessage(_oilQualityTooltip);

        return tooltip;
    }

    private void BindValues()
    {
        PowerIndicator.IsOn = IsPowered;

        OilMeter.MaximumValue = SolutionMaxVolume.Value;
        OilMeter.Value = SolutionVolume.Value;
        OilMeter.ForegroundColorOverride = SolutionColor.WithAlpha(0.8f);

        OilIndicator.IsOn = IsPowered && SolutionVolume < MinimumVolume;
        OilIndicator.ToolTip = OilIndicator.IsOn ? Loc.GetString("deep-fryer-ui-oil-tooltip", ("units", MinimumVolume)) : null;

        var (color, labelName) = GetOilQualityInfo();
        _oilQualityTooltip = FormattedMessage.FromMarkupPermissive(Loc.GetString("deep-fryer-oil-quality-examine",
            ("color", color.ToHex()),
            ("state", labelName)));

        BasketControl.HideTooltip();

        FryerBaskets.Contents = CookingItems;
        FryerBaskets.Capacity = Capacity;
    }
}
