using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Fax;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DV.Silicons;

[GenerateTypedNameReferences]
public sealed partial class StationAiFaxPageWindow : FancyWindow
{
    public event Action? RefreshButtonPressed;
    public event Action<string>? PeerSelected;
    public event Action<EntityUid>? SendButtonPressed;

    public StationAiFaxPageWindow(EntityUid uid, IEntityManager entityManager)
    {
        RobustXamlLoader.Load(this);
        SendingLabel.Text = entityManager.PaperName(uid);

        RefreshButton.OnPressed += _ => RefreshButtonPressed?.Invoke();
        SendButton.OnPressed += _ => SendButtonPressed?.Invoke(uid);
        PeerSelector.OnItemSelected += args =>
            PeerSelected?.Invoke((string) args.Button.GetItemMetadata(args.Id)!);
    }

    public void UpdateState(FaxUiState state)
    {
        SendButton.Disabled = !state.CanSendCooldown;
        FromLabel.Text = state.DeviceName;

        if (state.AvailablePeers.Count == 0)
        {
            PeerSelector.AddItem(Loc.GetString("fax-machine-ui-no-peers"));
            PeerSelector.Disabled = true;
        }

        if (PeerSelector.Disabled && state.AvailablePeers.Count != 0)
        {
            PeerSelector.Clear();
            PeerSelector.Disabled = false;
        }

        // always must be selected destination
        if (string.IsNullOrEmpty(state.DestinationAddress) && state.AvailablePeers.Count != 0)
        {
            PeerSelected?.Invoke(state.AvailablePeers.First().Key);
            return;
        }

        if (state.AvailablePeers.Count != 0)
        {
            PeerSelector.Clear();

            foreach (var (address, name) in state.AvailablePeers)
            {
                var id = AddPeerSelect(name, address);
                if (address == state.DestinationAddress)
                    PeerSelector.Select(id);
            }
        }
    }

    private int AddPeerSelect(string name, string address)
    {
        PeerSelector.AddItem(name);
        PeerSelector.SetItemMetadata(PeerSelector.ItemCount - 1, address);
        return PeerSelector.ItemCount - 1;
    }
}
