using Content.Shared._DV.Traitor;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DV.Traitor.UI;

[GenerateTypedNameReferences]
public sealed partial class RansomListing : BoxContainer
{
    public event Action<NetEntity>? OnPurchase;

    private NetEntity _ent;
    private int _price;

    public RansomListing(RansomData data)
    {
        RobustXamlLoader.Load(this);

        _ent = data.Entity;
        _price = data.Price;

        PurchaseButton.Text = Loc.GetString("ransom-ui-purchase", ("name", data.Name));
        PriceLabel.Text = "$" + _price;

        PurchaseButton.OnPressed += _ => OnPurchase?.Invoke(_ent);
    }

    public void UpdateBalance(int balance)
    {
        PurchaseButton.Disabled = balance < _price;
    }
}
