using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DV.Abilities.Psionics;

[GenerateTypedNameReferences]
public sealed partial class EruptionWarning : FancyWindow
{
    public EruptionWarning()
    {
        RobustXamlLoader.Load(this);

        ConfirmButton.OnPressed += _ => Close();
    }
}
