using System.Linq;
using Content.Client.Computer;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.CCVar;
using Content.Shared.Parallax.Biomes;
using Content.Shared.Procedural;
using Content.Shared.Salvage;
using Content.Shared.Salvage.Expeditions;
using Content.Shared.Salvage.Expeditions.Modifiers;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._DV.Salvage.UI;

[GenerateTypedNameReferences]
public sealed partial class MagnetOfferingWindowReleaseButton : Button
{
    public event Action<BaseButton.ButtonEventArgs>? ReleasePressed;

    public enum ButtonState { Disabled, Enabled, Enabling, InProgress };

    public MagnetOfferingWindowReleaseButton()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ReleaseButton.OnPressed += args =>
        {
            ReleasePressed?.Invoke(args);
        };
    }

    //don't keep setting text!
    public ButtonState State
    {
        set
        {
            switch (value)
            {
                case ButtonState.Disabled:
                    ReleaseButton.Disabled = true;
                    ReleaseButton.Text = Loc.GetString("magnet-offering-window-inactive");
                    WantsNegative = false;
                    break;
                case  ButtonState.Enabled:
                    ReleaseButton.Disabled = false;
                    ReleaseButton.Text = Loc.GetString("magnet-offering-window-release");
                    WantsNegative = false;
                    break;
                case  ButtonState.Enabling:
                    ReleaseButton.Disabled = true;
                    ReleaseButton.Text = Loc.GetString("magnet-offering-window-waiting");
                    WantsNegative = false;
                    break;
                case  ButtonState.InProgress:
                    ReleaseButton.Disabled = true;
                    ReleaseButton.Text = Loc.GetString("magnet-offering-window-releasing");
                    WantsNegative = true;
                    break;
            }
        }
    }


    private bool WantsNegative
    {
        set
        {
            if (value && !ReleaseButton.HasStyleClass(((StyleClass.Negative))))
                ReleaseButton.AddStyleClass((StyleClass.Negative));
            else if (!value && ReleaseButton.HasStyleClass(((StyleClass.Negative))))
                ReleaseButton.RemoveStyleClass(((StyleClass.Negative)));
        }
    }




}
