using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.Configuration;

namespace Content.Client._DV.UserInterfaces.BuildInfo.Controls;

[GenerateTypedNameReferences]
public sealed partial class BuildInfoWindow : DefaultWindow
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public BuildInfoWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Version.ValueText = _cfg.GetCVar(CVars.BuildVersion);
        EngineVersion.ValueText = _cfg.GetCVar(CVars.BuildEngineVersion);
        Fork.ValueText = _cfg.GetCVar(CVars.BuildForkId);
        DownloadUrl.ValueText = _cfg.GetCVar(CVars.BuildDownloadUrl);
        BuildHash.ValueText = _cfg.GetCVar(CVars.BuildHash);
        BuildManifestUrl.ValueText = _cfg.GetCVar(CVars.BuildManifestUrl);
        BuildManifestHash.ValueText = _cfg.GetCVar(CVars.BuildManifestHash);
    }
}
