- type: antag
  id: Fugitive
  name: roles-antag-fugitive-name
  antagonist: true
  objective: roles-antag-fugitive-objective
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 1h

- type: antagSpecifier
  parent: RestrictedAntag
  id: Fugitive
  spawnerPrototype: SpawnPointFugitive
  pickPlayer: false
  startingGear: FugitiveGear
  roleLoadout:
  - RoleSurvivalStandard
  components:
    - type: RandomMetadata
      nameSegments:
      - NamesFakeHumanFirst
      - NamesFakeHumanLast
      nameFormat: name-format-standard
    - type: RandomHumanoidAppearance
      randomizeName: false
      keepGender: true
    - type: EmitSoundOnSpawn # fell out of the ceiling
      sound: /Audio/Effects/clang.ogg
  mindRoles:
  - MindRoleFugitive

- type: startingGear
  id: FugitiveGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPrisoner
    ears: ClothingHeadsetGrey
    gloves: ClothingHandsGlovesColorYellow
    back: ClothingBackpackSatchel
    shoes: ClothingShoesChameleonNoSlips
    id: PassengerPDA
  #innerClothingSkirt: ClothingUniformJumpskirtPrisoner # FIXME doesnt work
  inhand:
  - ToolboxElectricalFilled
  storage:
    back:
    - FugitiveStash
