- type: antag
  id: SynthesisSpecialist
  name: roles-antag-syndicate-synthesis-name
  objective: roles-antag-syndicate-synthesis-objective
  antagonist: true # making poisions and shit on demand is evil
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 24h
  - !type:RoleTimeRequirement
    role: JobChemist
    time: 2h
