using Content.Client.UserInterface.Controls;
using Content.Shared._DV.Reputation;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DV.Reputation.UI;

[GenerateTypedNameReferences]
public sealed partial class ContractsWindow : FancyWindow
{
    [Dependency] private EntityManager _entMan = default!;

    public event Action<int>? OnAccept;
    public event Action<int>? OnComplete;
    public event Action<int>? OnReject;

    public EntityUid Owner;

    public ContractsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateState()
    {
        if (!_entMan.TryGetComponent<ContractsComponent>(Owner, out var comp))
            return;

        if (comp.CurrentLevel is {} level)
            Level.Text = Loc.GetString(level.Name);
        Reputation.Text = $"{comp.Reputation} Reputation";

        Contracts.RemoveAllChildren();
        for (int i = 0; i < comp.Slots.Count; i++)
        {
            if (comp.Slots[i].ObjectiveTitle is {} title)
            {
                var contract = new Contract(title);
                Contracts.AddChild(contract);
                // TODO: green when objective is complete
            }
            else
            {
                Contracts.AddChild(new Label()
                {
                    Text = "< no contract active >"
                });
                // TODO: NextUnlock thing
            }
        }

        Offerings.RemoveAllChildren();
        for (int i = 0; i < comp.OfferingTitles.Count; i++)
        {
            var index = i;
            var offering = comp.OfferingTitles[i];
            var button = new Button()
            {
                Text = offering + " - 0 TC 0 REP" // TODO
            };
            button.OnPressed += _ => OnAccept?.Invoke(index);
            Offerings.AddChild(button);
        }
    }
}
