using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DV.Reputation.UI;

/// <summary>
/// Contract control placed in a slot that has a contract active.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class Contract : BoxContainer
{
    public event Action OnComplete;
    public event Action OnReject;

    public ContractsWindow(string title)
    {
        RobustXamlLoader.Load(this);

        Title.text = title;

        CompleteButton.OnPressed += _ => OnComplete?.Invoke();
        RejectButton.OnPressed += _ => OnReject?.Invoke();

        OnComplete += () => Orphan();
        OnReject += () => Orphan();
    }
}
