using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DV.Reputation.UI;

/// <summary>
/// Contract control placed in a slot that has a contract active.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class Contract : BoxContainer
{
    public event Action? OnComplete;

    public Contract(string title)
    {
        RobustXamlLoader.Load(this);

        Title.Text = title;

        CompleteButton.OnPressed += _ => OnComplete?.Invoke();
    }
}
