- type: job
  id: Marshal
  name: job-name-marshal
  description: job-description-marshal
  playTimeTracker: JobMarshal
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 20h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 5h
    - !type:DepartmentTimeRequirement
      department: Justice
      time: 10h
  startingGear: MarshalGear
  alwaysUseSpawner: true
  canBeAntag: false
  icon: "JobIconMarshal"
  supervisors: job-supervisors-warden
  setPreference: true
  whitelisted: true
  access:
  - Justice
  - Prosecutor
  - Maintenance

  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

    # TODO: custom PDA and clothing
- type: startingGear
  id: MarshalGear
  equipment:
    id: PrisonGuardPDA
    ears: ClothingHeadsetJustice
    belt: ClothingBeltSecurity
  storage:
    back:
    - Flash

# DeltaV
- type: chameleonOutfit
  id: MarshalChameleonOutfit
  job: Marshal
  hasMindShield: true
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: PrisonGuardPDA
    ears: ClothingHeadsetJustice
    head: ClothingHeadPrisonGuard
    jumpsuit: ClothingUniformJumpsuitPrisonGuard
    mask: ClothingMaskGasSecurity
    gloves: ClothingHandsGlovesColorBlack
