using Content.Client.UserInterface.Controls;
using Content.Shared.DeltaV.QuickPhrase;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.DeltaV.AACTablet.UI;

[GenerateTypedNameReferences]
public sealed partial class AACWindow : FancyWindow
{
    private IPrototypeManager _prototypeManager;

    public AACWindow(AACBoundUserInterface ui, IPrototypeManager prototypeManager)
    {
        RobustXamlLoader.Load(this);
        _prototypeManager = prototypeManager;
        CreatePhraseButtons(ui);
    }

    private void CreatePhraseButtons(AACBoundUserInterface ui)
    {
        var loc = IoCManager.Resolve<ILocalizationManager>();
        var phrases = _prototypeManager.EnumeratePrototypes<QuickPhrasePrototype>();
        foreach (var phrase in phrases)
        {
            var text = loc.GetString(phrase.Text);
            var phraseLabel = new Label
            {
                Text = text
            };
            Body.AddChild(phraseLabel);
        }
    }
}
