using Content.Client.UserInterface.Controls;
using Content.Shared._DV.Objectives.Eui;
using Content.Shared.Mind;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._DV.Objectives.Eui;

[GenerateTypedNameReferences]
public sealed partial class ObjectiveEditorUi : FancyWindow
{
    private Dictionary<string, List<ObjectiveData>> _objectives = new();

    public ObjectiveEditorUi()
    {
        RobustXamlLoader.Load(this);
        NewObjectiveButton.OnPressed += _ => AddNewObjective();
    }

    private void AddNewObjective()
    {
    }

    public void SetRoles(ProtoId<RoleTypePrototype>? role, LocId? subtype)
    {
        RoleDescription.Text = role.HasValue ? role.Value.Id.ToString() : "No role?";
    }

    public void SetObjectives(Dictionary<string, List<ObjectiveData>> data)
    {
        _objectives = data;
        ObjectiveContainer.RemoveAllChildren();
        var index = 0;
        foreach (var (issuer, objectives) in data)
        {
            foreach (var objective in objectives)
            {
                var objectiveControl = new ObjectiveContainer(objective);
                index++;

                ObjectiveContainer.AddChild(objectiveControl);
            }
        }
    }
}
