using Content.Shared._DV.Objectives.Eui;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._DV.Objectives.Eui;

[GenerateTypedNameReferences]
public sealed partial class ObjectiveContainer : BoxContainer
{
    private ObjectiveData _objective;

    public event Action<ObjectiveData>? DeleteAction;

    public ObjectiveContainer(ObjectiveData objective)
    {
        RobustXamlLoader.Load(this);

        _objective = objective;

        ObjectiveContent.OnTextChanged += _ => _objective.Info.Description = Rope.Collapse(ObjectiveContent.TextRope).Trim();
        ObjectiveContent.Placeholder = new Rope.Leaf(Loc.GetString("objective-editor-ui-placeholder"));
        ObjectiveContent.TextRope = new Rope.Leaf(_objective.Info.Description);
        Delete.OnPressed += _ => DeleteAction?.Invoke(_objective);
    }
}
