using Content.Client.UserInterface.Controls;
using Content.Shared._DV.Objectives.Eui;
using Content.Shared.Mind;
using Content.Shared.Objectives;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._DV.Objectives.Eui;

[GenerateTypedNameReferences]
public sealed partial class ObjectiveEditorUi : FancyWindow
{
    private Dictionary<string, List<ObjectiveData>> _objectives = new();

    public ObjectiveEditorUi()
    {
        RobustXamlLoader.Load(this);
        NewObjectiveButton.OnPressed += _ => AddNewObjective();
        DeleteAllButton.OnPressed += _ => ObjectiveContainer.RemoveAllChildren();
        ResetButton.OnPressed += _ => SetObjectives(_objectives);
    }

    public Dictionary<string, List<ObjectiveData>> GetObjectives()
    {
        var objectives = new Dictionary<string, List<ObjectiveData>>();
        foreach (var child in ObjectiveContainer.Children)
        {
            if (child is not ObjectiveContainer objective)
                continue;

            var (issuer, data) = objective.GetData();
            objectives.GetOrNew(issuer).Add(data);
        }

        return objectives;
    }

    public void SetRoleDescription(ProtoId<RoleTypePrototype>? role, LocId? subtype)
    {
        var roleText = role.HasValue ? role.Value.Id.ToString() : "N/A";
        if (subtype.HasValue)
        {
            roleText += string.Format(" - {0}", Loc.GetString(subtype));
        }

        Title = Loc.GetString("objective-editor-admin-ui-title-filled", ("name", "The Admin"), ("role", roleText));
    }

    public void SetObjectives(Dictionary<string, List<ObjectiveData>> data)
    {
        _objectives = data;
        ObjectiveContainer.RemoveAllChildren();
        var index = 0;
        foreach (var (issuer, objectives) in data)
        {
            foreach (var objective in objectives)
            {
                var objectiveControl = new ObjectiveContainer(issuer, objective);

                ObjectiveContainer.AddChild(objectiveControl);

                index++;
            }
        }
    }

    private void AddNewObjective()
    {
        var newObjective = new ObjectiveInfo(
            Title: Loc.GetString("objective-editor-admin-ui-placeholder-title"),
            Description: Loc.GetString("objective-editor-admin-ui-placeholder-description"),
            Icon: SpriteSpecifier.Invalid, // TOOD(Barry): Probably something to think about rendering
            Progress: 0 // TODO(Barry): We need to probably do something with this
        );

        var objectiveControl = new ObjectiveContainer(
            Loc.GetString("objective-editor-admin-ui-placeholder-issuer"),
            new ObjectiveData(null, newObjective));

        ObjectiveContainer.AddChild(objectiveControl);
    }

    private void DeleteObjective(int index)
    {
    }
}
