using Content.Shared.Silicons.Borgs;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._CD.Silicons.Borgs.UI;

[GenerateTypedNameReferences]
public sealed partial class ChassisSpriteSelection : Control
{
    [Dependency] private readonly IComponentFactory _componentFactory = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public EntityPrototype? SubtypePrototype;
    public event Action? SubtypeSelected;

    private const int PrototypeViewSize = 2;
    private static readonly ProtoId<EntityCategoryPrototype> BorgSubtypeCategory = "BorgSubtype";

    public ChassisSpriteSelection()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Update(BorgTypePrototype borgTypePrototype)
    {
        MainContainer.Visible = true;

        OptionsContainer.RemoveAllChildren();

        var buttonGroup = new ButtonGroup();
        List<Button> buttons = new List<Button>();

        foreach (var ent in _prototype.Categories.GetValueRefOrNullRef(BorgSubtypeCategory))
        {
            if (!ent.TryGetComponent<Shared._CD.Silicons.Borgs.BorgSubtypeDefinitionComponent>(out var subtype, _componentFactory))
                continue;

            // Only add subtypes of the current selected 'main' borg type (engineering, medical, etc.)
            if (subtype.ParentType != borgTypePrototype.ID)
                continue;

            var button = new Button
            {
                ToolTip = Loc.GetString($"al-borg-{borgTypePrototype.ID}-subtype-{ent.Name.Replace(' ', '-').ToLower()}-name"),
                Group = buttonGroup,
                MinHeight = 32,
            };

            button.OnPressed += _ =>
            {
                SubtypePrototype = ent;
                SubtypeSelected?.Invoke();
            };

            button.AddChild(CreateEntityPrototypeView(subtype.DummyPrototype));
            buttons.Add(button);
        }

        foreach (var button in buttons)
        {
            OptionsContainer.AddChild(button);
        }
    }

    private EntityPrototypeView CreateEntityPrototypeView(EntProtoId entProtoId)
    {
        var entPrototypeView = new EntityPrototypeView();

        entPrototypeView.SetPrototype(entProtoId);
        entPrototypeView.Scale *= PrototypeViewSize;

        return entPrototypeView;
    }
}
