- type: gameMapPool
  id: DefaultMapPool
  maps:
# DeltaV
  - Arena
  - Academy
  - Anvil
  - Asterisk
  - Byoin
  - Chibi
  - Division
  - Edge
  - Elegance
  - Glacier
#  - Hammurabi - undergoing extensive maintenance
  - Lighthouse
#  - Micro - to be revisited later ~Colin
  - Pebble
  - Shoukou
  - Submarine
  - Terra
  - TheHive
  - Tortuga
