- type: department
  id: Logistics # DeltaV - Logistics Department replacing Cargo
  name: department-Logistics # DeltaV
  description: department-Logistics-description # DeltaV
  color: "#A46106"
  radioChannel: Supply # DeltaV
  roles:
  - CargoTechnician
  - Quartermaster
  - SalvageSpecialist
  # BEGIN DeltaV Logistics Jobs
  - Courier
  - CargoAssistant
  # END DeltaV

- type: department
  id: Civilian
  name: department-Civilian
  description: department-Civilian-description
  color: "#9FED58"
  radioChannel: Service # DeltaV
  weight: -10
  roles:
  - Bartender
  - Botanist
  # - Chaplain # DeltaV - Move Chaplain into Epistemics
  - Chef
  - Clown
  - HeadOfPersonnel
  - Janitor
  # - Lawyer # DeltaV - Move Lawyer into Justice
  # - Librarian # DeltaV - Move Librarian into Epistemics
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Visitor
  - ServiceWorker
  # BEGIN DeltaV Jobs
  - Boxer
  - MartialArtist
  - Zookeeper
  # END DeltaV

- type: department
  id: CentralCommand
  name: department-CentralCommand
  description: department-CentralCommand-description
  color: "#0c344d"
  radioChannel: CentCom # DeltaV
  roles:
  - CentralCommandOfficial
  - CBURN
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
  - DeathSquad
  editorHidden: true
  weight: 120

- type: department
  id: Command
  name: department-Command
  description: department-Command-description
  color: "#334E6D"
  radioChannel: Command # DeltaV
  roles:
  - Captain
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfPersonnel
  - HeadOfSecurity
  - ResearchDirector
  - Quartermaster
  - ChiefJustice # DeltaV - chief justice is in command staff
  - CentralCommandOfficial
  - CBURN
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
  - DeathSquad
  - StationAi # DeltaV - added for playtime trackers
  primary: false
  weight: 100

- type: department
  id: Engineering
  name: department-Engineering
  description: department-Engineering-description
  color: "#EFB341"
  radioChannel: Engineering # DeltaV
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - StationEngineer
  - TechnicalAssistant

- type: department
  id: Medical
  name: department-Medical
  description: department-Medical-description
  color: "#52B4E9"
  radioChannel: Medical # DeltaV
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  - Paramedic
  # BEGIN DeltaV Med Jobs
  - MedicalBorg
  - Surgeon
  # END DeltaV

- type: department
  id: Security
  name: department-Security
  description: department-Security-description
  color: "#1563bdC8" # DeltaV changed to blue, was "#DE3A3A"
  radioChannel: Security # DeltaV
  weight: 20
  roles:
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  - Detective
  - Warden
  # BEGIN DeltaV Sec Jobs
  - Brigmedic
  - PrisonGuard
  - SecurityBorg
  - RoleLaika 
  - RoleK9Officer
  # END DeltaV

- type: department
  id: Epistemics # DeltaV - Epistemics Department replacing Science
  name: department-Epistemics # DeltaV
  description: department-Epistemics-description # DeltaV
  color: "#D381C9"
  radioChannel: Science # DeltaV
  roles:
  - ResearchDirector
  - Scientist
  - ResearchAssistant
  # BEGIN DeltaV Epi Jobs
  - Chaplain # Moved from Service into Epi
  - ForensicMantis
  - Librarian # Curator, moved from Service into Epi
  - Roboticist
  # END DeltaV

- type: department
  id: Silicon
  name: department-Silicon
  description: department-Silicon-description
  color: "#D381C9"
  roles:
  - Borg
  - StationAi
  # BEGIN DeltaV Silicon Jobs
  - MedicalBorg
  - SecurityBorg
  # END DeltaV
  primary: false # DeltaV - removed from primary dept

# DeltaV - get rid of 'station-specific' as a department. All of these
#          jobs are under another category, so all this does is list
#          them twice in the job select and on the crew monitor.
# - type: department
#   id: Specific
#   name: department-Specific
#   description: department-Specific-description
#   color: "#9FED58"
#   weight: 10
#   roles:
#   - Reporter
#   - Psychologist
#   primary: false
# END DeltaV