[game]
hostname         = "[EN][MRP] Delta-V (Ψ) | Inclination [EU West]"
soft_max_players = 50

[adminlogs]
server_name = "Inclination"

[server]
rules_file   = "DeltaVRuleset"

[vote]
preset_enabled = true
map_enabled = true

[ooc]
enable_during_round = true

[hub]
tags = "lang:en-US,region:eu_w,rp:med,no_tag_infer"
