[game]
hostname         = "[EN][MRP] Delta-V (Ψ) | Meridian [EU West]"
soft_max_players = 40

[adminlogs]
server_name = "Meridian"

[hub]
tags = "lang:en-US,region:eu_w,rp:med,no_tag_infer"

[debug]
pow3r_disable_parallel = false
