- type: startingGear
  parent: CBURNGear
  id: CBURNGearDeltaV
  equipment:
    eyes: ClothingEyesERTInformationHud
    pocket1: WeaponPistolUniversalIncendiary
    pocket2: WeaponAdvancedLaser
    belt: ClothingBeltMilitaryWebbing
    shoes: ClothingShoesBootsERTMagboots
  storage:
    back:
    - WeaponShotgunKammererIncendiary
    - BoxShotgunIncendiary
    - BoxShotgunIncendiary
    - MagazineBoxMagnumIncendiary
    - MagazineBoxMagnumIncendiary
    - PillAmbuzolPlus
    - PillAmbuzol
    - CombatKnife
    belt:
    - MagazineUniversalMagnumIncendiary
    - MagazineUniversalMagnumIncendiary
    - GrenadeFlashBang
    - GrenadeFlashBang
    - GrenadeFlashBang
    - JawsOfLife
