using Content.Client.Options.UI;
using Content.Shared._DV.CCVars;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;

namespace Content.Client._DV.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class RadioTab : Control
{
    [Dependency] private readonly IConfigurationManager _config = default!; // DeltaV

    public RadioTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // Having so many color sliders on one page is a lot. We should only really try
        // to have common/departmental channels here, or it just becomes WAAAAY too much.
        Control.AddOptionColorSlider(DCCVars.RadioColorCommon, RadioCommonColorSlider);
        Control.AddOptionColorSlider(DCCVars.RadioColorCommand, RadioCommandColorSlider);
        Control.AddOptionColorSlider(DCCVars.RadioColorSecurity, RadioSecurityColorSlider);
        Control.AddOptionColorSlider(DCCVars.RadioColorMedical, RadioMedicalColorSlider);
        Control.AddOptionColorSlider(DCCVars.RadioColorEngineering, RadioEngineeringColorSlider);
        Control.AddOptionColorSlider(DCCVars.RadioColorScience, RadioScienceColorSlider);
        Control.AddOptionColorSlider(DCCVars.RadioColorCargo, RadioCargoColorSlider);
        Control.AddOptionColorSlider(DCCVars.RadioColorService, RadioServiceColorSlider);
        Control.AddOptionColorSlider(DCCVars.RadioColorBinary, RadioBinaryColorSlider);
        Control.AddOptionColorSlider(DCCVars.RadioColorJustice, RadioJusticeColorSlider);
        Control.AddOptionColorSlider(DCCVars.RadioColorPrison, RadioPrisonColorSlider);

        ResetCommonColorButton.OnPressed += _ => OnResetColorButton(DCCVars.RadioColorCommon);
        ResetCommandColorButton.OnPressed += _ => OnResetColorButton(DCCVars.RadioColorCommand);
        ResetSecurityColorButton.OnPressed += _ => OnResetColorButton(DCCVars.RadioColorSecurity);
        ResetMedicalColorButton.OnPressed += _ => OnResetColorButton(DCCVars.RadioColorMedical);
        ResetEngineeringColorButton.OnPressed += _ => OnResetColorButton(DCCVars.RadioColorEngineering);
        ResetScienceColorButton.OnPressed += _ => OnResetColorButton(DCCVars.RadioColorScience);
        ResetCargoColorButton.OnPressed += _ => OnResetColorButton(DCCVars.RadioColorCargo);
        ResetServiceColorButton.OnPressed += _ => OnResetColorButton(DCCVars.RadioColorService);
        ResetBinaryColorButton.OnPressed += _ => OnResetColorButton(DCCVars.RadioColorBinary);
        ResetJusticeColorButton.OnPressed += _ => OnResetColorButton(DCCVars.RadioColorJustice);
        ResetPrisonColorButton.OnPressed += _ => OnResetColorButton(DCCVars.RadioColorPrison);

        Control.Initialize();
    }

    private void OnResetColorButton(CVarDef<string> cvar)
    {
        _config.SetCVar(cvar, cvar.DefaultValue);
        Control.ReloadValues();
    }
}
