- type: entity
  parent: BaseMachineCircuitboard
  id: WashingMachineCircuitboard
  name: Nanotrasen Commercial Model-C washing machine board
  description: A machine printed circuit board for an industrial-grade washing machine.
  components:
  - type: MachineBoard
    prototype: WashingMachine
    stackRequirements:
      Steel: 1
      Manipulator: 1
      Cable: 1
