using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._DV.AccountLinking;

[GenerateTypedNameReferences]
public sealed partial class LinkAccountWindow : DefaultWindow
{
    public LinkAccountWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
