#Misc outfit startingGear definitions.

# Laika sec glasses

- type: startingGear
  id: MobSecDogLaikaGear
  equipment:
    eyes: ClothingEyesGlassesSunglasses
    outerClothing: ClothingOuterArmorDuraVestK9

- type: startingGear
  id: MobSilviaGear
  equipment:
    eyes: ClothingEyesHudMedical

#Oldstation Roles

- type: startingGear
  id: OldstationMedic
  equipment:
    jumpsuit: ClothingUniformJumpsuitMedicalDoctor
    neck: ClothingNeckStethoscope
    shoes: ClothingShoesColorWhite
    id: MedicalIDCard
    pocket1: Brutepack
    pocket2: GlowstickBase
    belt: ClothingBeltMedical


- type: startingGear
  id: OldstationGuard
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    shoes: ClothingShoesBootsJack
    id: SecurityIDCard
    pocket1: Flash
    pocket2: GlowstickBase

- type: startingGear
  id: OldstationEngi
  equipment:
    jumpsuit: ClothingUniformJumpsuitEngineering
    shoes: ClothingShoesBootsWork
    id: EngineeringIDCard
    mask: ClothingMaskBreath
    gloves: ClothingHandsGlovesColorYellowBudget
    pocket1: EmergencyOxygenTankFilled
    pocket2: GlowstickBase
    belt: ClothingBeltUtility

- type: startingGear
  id: OldstationScientist
  equipment:
    jumpsuit: ClothingUniformJumpsuitScientist
    shoes: ClothingShoesColorWhite
    id: ResearchIDCard
    pocket1: Pen
    pocket2: GlowstickBase

#Syndicate Pirate Radio Listener

- type: startingGear
  id: SyndicateListenerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPyjamaSyndicateBlack
    head: ClothingHeadPyjamaSyndicateBlack
    ears: ClothingHeadsetAltSyndicateListening
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesSlippers
    id: SyndiListeningPostPDA
    back: ClothingBackpackSyndicate
    pocket1: AgentIDCard
    pocket2: HandheldStationMapRecordsTablet
#  innerClothingSkirt: ClothingUniformJumpsuitPyjamaSyndicatePink # I don't think loadouts work for ghost roles anyways

# Syndicate Synthesis Gear
- type: startingGear
  id: SyndicateSynthesisGear
  equipment:
    jumpsuit: ClothingUniformInterdyneChemist
    back: ClothingBackpackChemistry
    belt: ChemBag
    eyes: ClothingEyesGlassesChemicalInterdyne
    gloves: ClothingHandsGlovesChemist
    outerClothing: ClothingOuterInterdyneChemistrySuit
    shoes: ClothingShoesEnclosedChem
    id: SyndiPDA
    ears: ClothingHeadsetAltSyndicateInterdyne # Gives them Traffic Coms (Todo: Add common coms upon ship & role rework)
    pocket1: HandLabeler
    pocket2: RubberStampSyndicate
    mask: ClothingMaskInterdyneChemistry
    head: ClothingHeadHatSyndie
  inhand:
    - DefibrillatorSyndicate

# Arms Dealer Gear
- type: startingGear
  id: SyndicateArmsDealerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitJeansBrown
    back: ClothingBackpackSatchelLeather
    belt: ClothingBeltHolsterArmsdealerFilled
    eyes: ClothingEyesGlassesCheapSunglasses
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterCoatJensen
    shoes: ClothingShoesBootsLaceup
    id: SyndiPDA
    ears: ClothingHeadsetAltSyndicateInterdyne
    mask: ClothingMaskNeckGaiter
    head: ClothingHeadHatFedoraBlack
  inhand:
  - BriefcaseRecruiterArmsdealer

