using System.Linq;
using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeltaV.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class StockTradingUiFragment : BoxContainer
{
    private readonly Dictionary<string, CompanyEntry> _companyEntries = new();

    public StockTradingUiFragment()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(StockTradingUiState state)
    {
        NoEntries.Visible = state.Entries.Count == 0;
        Balance.Text = $"Balance: {state.Balance:F2} credits";

        // Remove old entries
        foreach (var key in _companyEntries.Keys.ToList().Where(key => state.Entries.All(e => e.Name != key)))
        {
            _companyEntries[key].Container.RemoveAllChildren();
            _companyEntries.Remove(key);
        }

        // Update or add new entries
        foreach (var company in state.Entries)
        {
            if (!_companyEntries.TryGetValue(company.Name, out var entry))
            {
                entry = new CompanyEntry();
                _companyEntries[company.Name] = entry;
                Entries.AddChild(entry.Container);
            }

            var ownedStocks = state.OwnedStocks.GetValueOrDefault(company.Name, 0);
            entry.Update(company, ownedStocks);
        }
    }

    private sealed class CompanyEntry
    {
        public readonly BoxContainer Container;
        private readonly Label _nameLabel;
        private readonly Label _priceLabel;
        private readonly Label _changeLabel;
        private readonly Button _sellButton;
        private readonly Label _sharesLabel;

        public CompanyEntry()
        {
            Container = new BoxContainer
            {
                Orientation = LayoutOrientation.Vertical,
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 10),
                StyleClasses = { "StockEntry" },
            };

            var topRow = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };

            _nameLabel = new Label
            {
                HorizontalExpand = true,
                StyleClasses = { "CompanyName" },
            };
            _priceLabel = new Label
            {
                MinWidth = 80,
                StyleClasses = { "StockPrice" },
            };
            _changeLabel = new Label
            {
                MinWidth = 80,
                StyleClasses = { "PriceChange" },
            };

            topRow.AddChild(_nameLabel);
            topRow.AddChild(_priceLabel);
            topRow.AddChild(_changeLabel);

            var bottomRow = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 5, 0, 0),
            };

            var amountEdit = new LineEdit
            {
                PlaceHolder = "Amount",
                HorizontalExpand = true,
                MinWidth = 60,
            };

            var buyButton = new Button
            {
                Text = "Buy",
                MinWidth = 60,
                StyleClasses = { "BuyButton" },
            };

            _sellButton = new Button
            {
                Text = "Sell",
                MinWidth = 60,
                StyleClasses = { "SellButton" },
            };

            _sharesLabel = new Label
            {
                Text = "Owned: 0",
                StyleClasses = { "SharesOwned" },
            };

            bottomRow.AddChild(_sharesLabel);
            bottomRow.AddChild(amountEdit);
            bottomRow.AddChild(buyButton);
            bottomRow.AddChild(_sellButton);

            Container.AddChild(topRow);
            Container.AddChild(bottomRow);
        }

        public void Update(StockCompanyStruct company, int ownedStocks)
        {
            _nameLabel.Text = company.Name;
            _priceLabel.Text = $"{company.CurrentPrice:F2}";
            _sharesLabel.Text = $"Owned: {ownedStocks}";

            var priceChange = 0f;
            if (company.PriceHistory.Count > 0)
            {
                var previousPrice = company.PriceHistory[^1];
                priceChange = ((company.CurrentPrice - previousPrice) / previousPrice) * 100;
            }

            _changeLabel.Text = $"{priceChange:F2}%";
            _changeLabel.StyleClasses.Remove("positive");
            _changeLabel.StyleClasses.Remove("negative");
            _changeLabel.StyleClasses.Add(priceChange >= 0 ? "positive" : "negative");

            // Disable sell button if no shares owned
            _sellButton.Disabled = ownedStocks <= 0;
        }
    }
}
