using System.Numerics;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Client.UserInterface.Controls;

using Content.Shared._DV.Noospherics;

namespace Content.Client._DV.ParticleAccelerator.UI;

[GenerateTypedNameReferences]
public sealed partial class NoosphereParticleAcceleratorControlMenu : FancyWindow
{
    private const int MaxPowerLevel = 4;

    private sealed class ParticleUIData
    {
        public Color SelectedColor;
        public Color DefaultColor;
        public string Identifier = "?";
    };

    private Dictionary<ParticleType, ParticleUIData> _particleUIData = new()
    {
        { ParticleType.Delta, new ParticleUIData
          {
            SelectedColor = Color.FromHex("#d82c3f"),
            DefaultColor = Color.FromHex("#a82331"),
            Identifier = "δ",
          }
        },
        {
          ParticleType.Epsilon, new ParticleUIData
          {
            SelectedColor = Color.FromHex("#d6b1dd"),
            DefaultColor = Color.FromHex("#6F5973"),
            Identifier = "ε",
          }
        },
        { ParticleType.Omega, new ParticleUIData
          {
            SelectedColor = Color.FromHex("#e5c78e"),
            DefaultColor = Color.FromHex("#77684B"),
            Identifier = "ζ",
          }
        },
        { ParticleType.Zeta, new ParticleUIData
          {
            SelectedColor = Color.FromHex("#83a7e0"),
            DefaultColor = Color.FromHex("#556E95"),
            Identifier = "ω",
          }
        },
    };

    public NoosphereParticleAcceleratorControlMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        foreach (var type in Enum.GetValues<ParticleType>())
        {
            CreatePowerSettings(type);
            SetParticlePower(type, 0);
        }
    }

    private void CreatePowerSettings(ParticleType type)
    {
        var particleContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical

        };

        var buttonData = _particleUIData[type];
        var buttonSize = new Vector2(65f, 25f);

        // Reverse it so power goes Up
        for (var i = MaxPowerLevel; i > 0; --i)
        {
            var levelButton = new Button()
            {
                SetSize = buttonSize,
                Margin = new Thickness(2.5f, 3f),
                Modulate = buttonData.DefaultColor
            };

            var index = i;
            levelButton.OnPressed += _ =>
            {
                SetParticlePower(type, index);
            };

            particleContainer.AddChild(levelButton);
        }

        var notation = new Label
        {
            SetSize = buttonSize,
            VerticalAlignment = VAlignment.Bottom,
            HorizontalAlignment = HAlignment.Center,
            Align = Label.AlignMode.Center,
            Text = buttonData.Identifier
        };
        particleContainer.AddChild(notation);
        PowerContainer.AddChild(particleContainer);
    }

    private void SetParticlePower(ParticleType type, int level)
    {
        // TODO: Play audio sample of 'clicking' for the button
        var particleContainer = PowerContainer.GetChild((int)type);
        var buttonData = _particleUIData[type];
        for (var i = 0; i < MaxPowerLevel; ++i)
        {
            var powerButton = particleContainer.GetChild(i);
            if (level == i)
            {
                powerButton.Modulate = buttonData.SelectedColor;
            }
            else
            {
                powerButton.Modulate = buttonData.DefaultColor;
            }
        }
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.Move;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
    }
}
