# Jumpsuit
- type: loadout
  id: HeadofSecurityJumpsuitGrey
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSGrey
  groupBy: "jumpsuit"

- type: loadout
  id: HeadofSecurityJumpskirtGrey
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSGrey
  groupBy: "jumpskirt"

- type: loadout
  id: HeadofSecurityJumpsuitBlue
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSBlue
  groupBy: "jumpsuit"

- type: loadout
  id: HeadofSecurityJumpskirtBlue
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSBlue
  groupBy: "jumpskirt"


- type: loadout
  id: HeadofSecurityParadeSuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSParadeMale
  groupBy: "jumpsuit"

- type: loadout
  id: HeadofSecurityParadeSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSParadeMale
  groupBy: "jumpskirt"


# Head
- type: loadout
  id: HeadofSecurityCavalier
  equipment:
    head: ClothingHeadHatHeadOfSecurityCavalier

# OuterClothing
- type: loadout
  id: StasecWinterCoatHoS
  equipment:
    outerClothing: ClothingOuterCoatStasecHoS
  groupBy: "wintercoat"

- type: loadout
  id: HeadOfSecurityTrenchcoat
  equipment:
    outerClothing: ClothingOuterCoatHoSTrench

- type: loadout
  id: HeadofSecurityLongcoat
  equipment:
    outerClothing: ClothingLongcoatHoS
  groupBy: "longcoat"

# Shoes
- type: loadout
  id: HeadOfSecurityWinterBoots
  equipment:
    shoes: ClothingShoesBootsWinterHeadOfSecurity
  groupBy: "winterboots"

# Neck
- type: loadout
  id: HeadOfSecurityRobe
  effects:
   - !type:JobRequirementLoadoutEffect
    requirement:
      !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 180000
  equipment:
    neck: ClothingNeckHosRobe

- type: loadout
  id: HeadOfSecurityCloakBoat
  equipment:
    neck: ClothingNeckHeadOfSecurityCloakBoat
