- type: job
  id: SecurityK9Officer
  playTimeTracker: JobK9Officer
  name: job-name-k9-officer
  description: job-description-k9-officer
  icon: JobIconSecurityK9Officer
  setPreference: false
  supervisors: job-supervisors-hos
  access:
  - Security
  - Maintenance
  - External
  canBeAntag: false
