using System.Linq; // DeltaV - Used for `.First()` on channel sets.
// using System.Threading.Channels; // DeltaV - Unused.
using Content.Client.UserInterface.Controls;
using Content.Shared._DV.Radio.Components; // DeltaV - To use DVRadioToggleable type
using Content.Shared.Radio.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls; // DeltaV - To use Button type
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Radio.Ui;

[GenerateTypedNameReferences]
public sealed partial class IntercomMenu : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public event Action<bool>? OnMicPressed;
    public event Action<bool>? OnSpeakerPressed;
    public event Action<string>? OnChannelSelected;

    private readonly List<string> _channels = new();

    public IntercomMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        MicButton.OnPressed += args => OnMicPressed?.Invoke(args.Button.Pressed);
        SpeakerButton.OnPressed += args => OnSpeakerPressed?.Invoke(args.Button.Pressed);
    }

    /// <summary>
    /// DeltaV - Sets button's state based on component's presence and enabled-status.
    /// </summary>
    /// <param name="button">The button which state depends on the component</param>
    /// <param name="component">The component which defines the button's state</param>
    private void UpdateToggleButton(Button button, DVRadioToggleable? component)
    {
        if (component == null)
        {
            button.Disabled = true;
            return;
        }

        button.Disabled = false;
        button.Pressed = component.Enabled;
    }

    // BEGIN DeltaV - Add microphone and speaker component parameters to Update
    public void Update(EntityUid uid, IntercomComponent intercom, RadioMicrophoneComponent? microphone, RadioSpeakerComponent? speaker)
    {
        if (intercom.SupportedChannels.Count == 0)
        {
            MicButton.Disabled = true;
            SpeakerButton.Disabled = true;
            ChannelOptions.Disabled = true;
        }
        else
        {
            UpdateToggleButton(MicButton, microphone);
            UpdateToggleButton(SpeakerButton, speaker);
        }

        var currentChannel =
            microphone?.BroadcastChannel ??
            speaker?.Channels.First() ??
            intercom.SupportedChannels.First();
        // END DeltaV

        ChannelOptions.Clear();
        _channels.Clear();
        for (var i = 0; i < intercom.SupportedChannels.Count; i++) // DeltaV - Add microphone and speaker component parameters to Update
        {
            var channel = intercom.SupportedChannels[i]; // DeltaV - Add microphone and speaker component parameters to Update
            if (!_prototype.Resolve(channel, out var prototype))
                continue;

            _channels.Add(channel);
            ChannelOptions.AddItem(Loc.GetString(prototype.Name), i);

            if (channel == currentChannel) // DeltaV - Add microphone and speaker component parameters to Update
                ChannelOptions.Select(i);
        }

        if (intercom.SupportedChannels.Count == 0) // DeltaV - Add microphone and speaker component parameters to Update
        {
            ChannelOptions.AddItem(Loc.GetString("intercom-options-none"), 0);
            ChannelOptions.Select(0);
        }

        ChannelOptions.OnItemSelected += args =>
        {
            if (!_channels.TryGetValue(args.Id, out var proto))
                return;

            ChannelOptions.SelectId(args.Id);
            OnChannelSelected?.Invoke(proto);
        };
    }
}

