- type: antag
  id: Thief
  name: roles-antag-thief-name
  antagonist: true
  setPreference: true
  objective: roles-antag-thief-objective
  guides: [ Thieves ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 24h # DeltaV - was 1h

- type: antagSpecifier
  parent: RestrictedAntag
  id: Thief
  prefRoles:
  - Thief
  allowNonHumans: true
  multiAntagSetting: NotExclusive
  startingGear: ThiefGear
  # components:
  # - type: Pacified # DeltaV - forced pacifism is lame
  # - type: Thieving # DeltaV - remove innate thieving ability
  #  stripTimeReduction: 2
  #  stealthy: true
  mindRoles:
  - MindRoleThief
  briefing:
    sound: "/Audio/Misc/thief_greeting.ogg"

- type: startingGear
  id: ThiefGear
  storage:
    back:
    #- ThiefBeacon # DeltaV - no more objectives
    - SatchelThief
    - ClothingHandsChameleonThief # DeltaV - add back thieving gloves
