# SPDX-FileCopyrightText: 2021 Mith-randalf <84274729+Mith-randalf@users.noreply.github.com>
# SPDX-FileCopyrightText: 2021 Paul Ritter <ritter.paul1@googlemail.com>
# SPDX-FileCopyrightText: 2021 Peptide90 <78795277+Peptide90@users.noreply.github.com>
# SPDX-FileCopyrightText: 2021 Swept <sweptwastaken@protonmail.com>
# SPDX-FileCopyrightText: 2022 ElectroJr <leonsfriedrich@gmail.com>
# SPDX-FileCopyrightText: 2022 Emisse <99158783+Emisse@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Fishfish458 <47410468+Fishfish458@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Kara <lunarautomaton6@gmail.com>
# SPDX-FileCopyrightText: 2022 Rane <60792108+Elijahrane@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 T-Stalker <43253663+DogZeroX@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 T-Stalker <le0nel_1van@hotmail.com>
# SPDX-FileCopyrightText: 2022 Veritius <veritiusgaming@gmail.com>
# SPDX-FileCopyrightText: 2022 fishfish458 <fishfish458>
# SPDX-FileCopyrightText: 2022 ike709 <ike709@github.com>
# SPDX-FileCopyrightText: 2022 ike709 <ike709@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 metalgearsloth <metalgearsloth@gmail.com>
# SPDX-FileCopyrightText: 2022 theashtronaut <112137107+theashtronaut@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Alekshhh <44923899+Alekshhh@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Chief-Engineer <119664036+Chief-Engineer@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Jeff <velcroboy333@hotmail.com>
# SPDX-FileCopyrightText: 2023 Kevin Zheng <kevinz5000@gmail.com>
# SPDX-FileCopyrightText: 2023 Kit0vras <123590995+Kit0vras@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Lei Yunxing <lyx2020@sjtu.edu.cn>
# SPDX-FileCopyrightText: 2023 Nim <128169402+Nimfar11@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Puro <103608145+PuroSlavKing@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Scribbles0 <91828755+Scribbles0@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 SpaceCat <99134830+Verslebas@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Velcroboy <107660393+IamVelcroboy@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Whisper <121047731+QuietlyWhisper@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 deltanedas <@deltanedas:kde.org>
# SPDX-FileCopyrightText: 2023 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Agoichi <92464780+Agoichi@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Aviu00 <93730715+Aviu00@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Flareguy <78941145+Flareguy@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 HappyRoach <117393350+HappyRoach@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Icepick <122653407+Icepicked@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 IlyaElDunaev <154531074+IlyaElDunaev@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 LankLTE <135308300+LankLTE@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Moomoobeef <62638182+Moomoobeef@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Nairod <110078045+Nairodian@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Plykiya <58439124+Plykiya@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 PoTeletubby <ajcraigaz@gmail.com>
# SPDX-FileCopyrightText: 2024 Ty Ashley <42426760+TyAshley@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 crazybrain23 <44417085+crazybrain23@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 deltanedas <39013340+deltanedas@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 kosticia <kosticia46@gmail.com>
# SPDX-FileCopyrightText: 2024 lzk <124214523+lzk228@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 marbow <152051971+marboww@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 starch <starchpersonal@gmail.com>
# SPDX-FileCopyrightText: 2024 to4no_fix <156101927+chavonadelal@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 2025 Aidenkrz <aiden@djkraz.com>
# SPDX-FileCopyrightText: 2025 Armok <155400926+ARMOKS@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 ArtisticRoomba <145879011+ArtisticRoomba@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 BombasterDS2 <shvalovdenis.workmail@gmail.com>
# SPDX-FileCopyrightText: 2025 BramvanZijp <56019239+BramvanZijp@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Creatorbot01 <creatorbot02@gmail.com>
# SPDX-FileCopyrightText: 2025 Creatorbot01 <creatorbot20@gmail.com>
# SPDX-FileCopyrightText: 2025 Fishbait <Fishbait@git.ml>
# SPDX-FileCopyrightText: 2025 Floxington <florian.decker@mailbox.org>
# SPDX-FileCopyrightText: 2025 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 2025 JORJ949 <159719201+JORJ949@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Killerqu00 <47712032+Killerqu00@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Lincoln McQueen <lincoln.mcqueen@gmail.com>
# SPDX-FileCopyrightText: 2025 SX-7 <92227810+SX-7@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 SX_7 <sn1.test.preria.2002@gmail.com>
# SPDX-FileCopyrightText: 2025 Solstice <solsticeofthewinter@gmail.com>
# SPDX-FileCopyrightText: 2025 Ted Lukin <66275205+pheenty@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Zokkie <6126135+Zokkie@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 fishbait <gnesse@gmail.com>
# SPDX-FileCopyrightText: 2025 gus <august.eymann@gmail.com>
# SPDX-FileCopyrightText: 2025 pheenty <fedorlukin2006@gmail.com>
# SPDX-FileCopyrightText: 2025 slarticodefast <161409025+slarticodefast@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: entity
  id: LockerWardenFilledHardsuit
  suffix: Filled, Hardsuit
  parent: LockerWarden
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - !type:NestedSelector
          tableId: FillLockerWarden
        - !type:NestedSelector
          tableId: FillLockerWardenHardsuit

- type: entity
  id: LockerWardenFilled
  suffix: Filled
  parent: LockerWarden
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillLockerWarden

- type: entityTable
  id: FillLockerWarden
  table: !type:AllSelector
    children:
    - id: FlashlightSeclite
    - id: WeaponDisabler
    - id: WeaponTaser
    - id: ClothingBeltSecurityFilled
    - id: Flash
    - id: ClothingEyesGlassesSecurity
    - id: ClothingHandsGlovesCombat
    #- id: ClothingShoesBootsJack # DeltaV - Moved to dresser
    #- id: ClothingOuterCoatWarden # DeltaV - removed for incongruence
    #- id: ClothingOuterWinterWarden # DeltaV - removed for incongruence
    - id: RubberStampWarden
    - id: DoorRemoteArmory
    - id: HoloprojectorSecurity
    #- id: BookSpaceLaw # DeltaV - Moved to dresser
    - id: ClothingBackpackElectropack
      amount: 2
    #- id: RemoteSignaller # DeltaV - Moved to dresser
    #  amount: 2
    #- id: NetworkConfigurator # DeltaV - Moved to dresser
    #- id: Binoculars # DeltaV - Moved to Dresser
    - id: WeaponEnergyShotgun
    # Begin DeltaV additions
    - id: BoxPDAPrisoner
    - id: BoxEncryptionKeyPrisoner
    - id: LunchboxSecurityFilledRandom
      prob: 0.3
    - id: ClothingOuterVestPlateCarrierAdv
    - id: ClothingHeadsetAltSecurity # Restored from upstream merge.
    #- id: ClothingNeckShockCollar # DeltaV - Moved to dresser I guess?
    #  amount: 2
    # End DeltaV additions
    - id: SecurityMegaphone # goob - loudspeakers


- type: entityTable
  id: FillLockerWardenHardsuit
  table: !type:AllSelector
    children:
    - id: ClothingOuterHardsuitCombatWarden # DeltaV - ClothingOuterHardsuitWarden replaced in favour of warden's riot combat hardsuit.
    - id: ClothingShoesBootsSecurityMagboots # DeltaV - Added security magboots.
    - id: OxygenTankFilled
    - id: NitrogenTankFilled
    - id: ClothingMaskBreath

- type: entity
  id: LockerSecurityFilled
  suffix: Filled
  parent: LockerSecurity
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillLockerSecurity

- type: entityTable
  id: FillLockerSecurity
  table: !type:AllSelector
    children:
    - !type:NestedSelector # DeltaV - Adds our modifications.
      tableId: FillLockerSecurityDeltaV
    - id: FlashlightSeclite
      prob: 0.8
    - id: WeaponDisabler
    - id: WeaponTaser
    #- id: ClothingUniformJumpsuitSecGrey # DeltaV - remove uniforms from sec lockers
    #  prob: 0.3
    - id: ClothingHeadHelmetBasic
    #- id: ClothingOuterArmorBasic # DeltaV - ClothingOuterArmorBasic replaced in favour of plate carrier and stabproof vest
    - id: ClothingBeltSecurityFilled
    - id: Flash
    #  prob: 0.5 # DeltaV - standardise spare flash
    - id: ClothingEyesGlassesSecurity
    - id: ClothingHeadsetSecurity
    - id: ClothingHandsGlovesColorBlack
    - id: ClothingShoesBootsJack
    - id: WeaponMeleeNeedle
      prob: 0.1
    - id: HoloprojectorSecurity
      prob: 0.6
    - id: BookSpaceLaw
      prob: 0.5

- type: entity
  id: LockerBrigmedicFilled
  suffix: Corpsman, Filled # DeltaV - rename brigmedic to corpsman
  parent: LockerBrigmedic
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillLockerBrigmedic

- type: entityTable
  id: FillLockerBrigmedic
  table: !type:AllSelector
    children:
    - !type:NestedSelector # DeltaV - Adds our modifications.
      tableId: FillLockerBrigmedicDeltaV
    - id: WeaponTaser
    - id: ClothingEyesGlassesCorpsman
    - id: WeaponDisabler
    - id: TrackingImplanter
      amount: 2
    # Begin DeltaV removal
    #- id: ClothingOuterHardsuitBrigmedic  # DeltaV - Moved to hardsuit entityTable under ClothingOuterHardsuitCombatCorpsman.
    #- id: BoxSterileMask
    #- id: ClothingHeadHatBeretCorpsman
    #- id: ClothingOuterCoatAMG # DeltaV - removed until I can resprite it or replace it.
    #- id: ClothingUniformJumpsuitBrigmedic
    #- id: ClothingUniformJumpskirtBrigmedic
    #- id: ClothingUniformJumpskirtOfLife
    #  prob: 0.1
    # End DeltaV removal
    - id: MedkitFilled
    - !type:GroupSelector
      prob: 0.7
      children:
      #- id: MedkitCombatFilled - DeltaV - doesn't need 2 or 3 of these
      #  weight: 1.6
      - id: MedkitAdvancedFilled
      - id: MedkitOxygenFilled
        weight: 0.8
      - id: MedkitBruteFilled
        weight: 0.8
      - id: MedkitToxinFilled
        weight: 0.8
      - id: MedkitBurnFilled
        weight: 1.8
    #- id: ClothingNeckCloakMoth #bzzz Moth-pocalypse # DeltaV - removed for incongruence
    #  prob: 0.15

- type: entity
  id: LockerDetectiveFilled
  suffix: Filled
  parent: LockerDetective
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillLockerDetective

- type: entityTable
  id: FillLockerDetective
  table: !type:AllSelector
    children:
    - !type:NestedSelector # DeltaV - Adds our modifications.
      tableId: FillLockerDetectiveDeltaV
    - id: ClothingEyesGlassesNoir
    # Begin DeltaV Removals - removed for incongruence
    #- id: ClothingHeadHatDetGadget
    #- id: ClothingNeckTieDet
    #- id: ClothingOuterVestDetective
    #- id: ClothingOuterCoatDetectiveLoadout
    # End DeltaV Removals
    - id: FlippoEngravedLighter
    - id: FlashlightSeclite
    - id: ForensicScanner
    - id: LogProbeCartridge
    - id: BoxForensicPad
    - id: DrinkDetFlask
    - id: ClothingHandsGlovesForensic
    - id: RubberStampDetective
    - id: HoloprojectorSecurity
    - id: BoxEvidenceMarkers
    - id: HandLabeler

- type: entity
  id: ClosetBombFilled
  parent: ClosetBomb
  suffix: Filled
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillClosetBomb

- type: entityTable
  id: FillClosetBomb
  table: !type:AllSelector
    children:
    - id: ClothingHeadHelmetBombSuit
    - id: ClothingOuterSuitBomb
    - id: Wirecutter
    - id: Screwdriver
    - id: Multitool
      prob: 0.5

- type: entity
  parent: [SecurityGunSafeNonlethalHandgunDV, BaseSecurityContraband] # DeltaV - Changed GunSafeBaseSecure with SecurityGunSafeNonlethalHandgunDV
  id: GunSafeDisabler
  name: disabler safe
  components:
  - type: EntityStorageVisuals # DeltaV Sprite
    stateDoorClosed: disabler
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeDisabler

- type: entityTable
  id: FillGunSafeDisabler
  table: !type:AllSelector
    children:
    - id: WeaponDisabler
      amount: 5

- type: entity
  parent: [SecurityGunSafeHandgunDV, BaseSecurityContraband]  # DeltaV - Changed GunSafeBaseSecure with SecurityGunSafeHandgunDV
  id: GunSafePistolMk58
  name: mk58 safe
  components:
  - type: EntityStorageVisuals # DeltaV Sprite
    stateDoorClosed: pistol
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafePistolMk58

- type: entityTable
  id: FillGunSafePistolMk58
  table: !type:AllSelector
    children:
    - id: WeaponPistolMk58
      amount: 4
    - id: MagazinePistol
      amount: 8

- type: entity
  parent: [SecurityGunSafeBaseSecureDV, BaseSecurityContraband] # DeltaV - Changed GunSafeBaseSecure with SecurityGunSafeBaseSecureDV
  id: GunSafeRifleLecter
  name: lecter safe
  components:
  - type: EntityStorageVisuals # DeltaV Sprite
    stateDoorClosed: lecter
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeRifleLecter

- type: entityTable
  id: FillGunSafeRifleLecter
  table: !type:AllSelector
    children:
    - id: WeaponRifleLecter
      amount: 2
    - id: MagazineRifle
      amount: 4

- type: entity
  parent: [SecurityGunSafeBaseSecureDV, BaseSecurityContraband] # DeltaV - Changed GunSafeBaseSecure with SecurityGunSafeBaseSecureDV
  id: GunSafeSubMachineGunDrozd
  name: drozd safe
  components:
  - type: EntityStorageVisuals # DeltaV Sprite
    stateDoorClosed: drozd
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeSubMachineGunDrozd

- type: entityTable
  id: FillGunSafeSubMachineGunDrozd
  table: !type:AllSelector
    children:
    - id: WeaponSubMachineGunDrozd
      amount: 2
    - id: MagazinePistolSubMachineGun
      amount: 4

- type: entity
  parent: [SecurityGunSafeBaseSecureDV, BaseSecurityContraband] # DeltaV - Changed GunSafeBaseSecure with SecurityGunSafeBaseSecureDV
  id: GunSafeShotgunEnforcer
  name: enforcer safe
  components:
  - type: EntityStorageVisuals # DeltaV Sprite
    stateDoorClosed: enforcer
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeShotgunEnforcer

- type: entityTable
  id: FillGunSafeShotgunEnforcer
  table: !type:AllSelector
    children:
    - id: WeaponShotgunEnforcer
      amount: 2
    - id: BoxLethalshot
      amount: 4

- type: entity
  parent: [SecurityGunSafeBaseSecureDV, BaseSecurityContraband] # DeltaV - Changed GunSafeBaseSecure with SecurityGunSafeBaseSecureDV
  id: GunSafeShotgunKammerer
  name: kammerer safe
  components:
  - type: EntityStorageVisuals # DeltaV Sprite
    stateDoorClosed: kammerer
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeShotgunKammerer

- type: entityTable
  id: FillGunSafeShotgunKammerer
  table: !type:AllSelector
    children:
    - id: WeaponShotgunKammerer
      amount: 2
    - id: BoxLethalshot
      amount: 4

- type: entity
  id: GunSafeSubMachineGunWt550
  suffix: Wt550
  parent: [SecurityGunSafeBaseSecureDV, BaseSecurityContraband] # DeltaV - Changed GunSafeBaseSecure with SecurityGunSafeBaseSecureDV
  name: wt550 safe
  components:
  - type: EntityStorageVisuals # DeltaV Sprite
    stateDoorClosed: wt550
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeSubMachineGunWt550

- type: entityTable
  id: FillGunSafeSubMachineGunWt550
  table: !type:AllSelector
    children:
    - id: WeaponSubMachineGunWt550
      amount: 2
    - id: MagazinePistolSubMachineGunTopMounted
      amount: 4

- type: entity
  parent: [SecurityGunSafeBaseSecureDV, BaseSecurityContraband]  # DeltaV - Changed GunSafeBaseSecure with SecurityGunSafeBaseSecureDV
  id: GunSafeLaserCarbine
  name: laser safe
  components:
  - type: EntityStorageVisuals # DeltaV Sprite
    stateDoorClosed: laser
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeLaserCarbine

- type: entityTable
  id: FillGunSafeLaserCarbine
  table: !type:AllSelector
    children:
    - id: WeaponLaserCarbine
      amount: 3
