using System;
using Content.Shared.Localizations;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Localization;

namespace Content.Client._DV.Administration.UI.Tabs.AdminTab
{
    [GenerateTypedNameReferences]
    public sealed partial class DVAdminShuttleWindow : DefaultWindow
    {
        public DVAdminShuttleWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            _callShuttleButton.OnPressed += OnPressed;
        }

        private void OnPressed(EventArgs obj) {
            var console = IoCManager.Resolve<IClientConsoleHost>();
            var loc = IoCManager.Resolve<ILocalizationManager>();

            if (!TimeSpan.TryParseExact(_callShuttleTime.Text, ContentLocalizationManager.TimeSpanMinutesFormats, loc.DefaultCulture, out _))
                return;

            if (_callShuttleRecallable.Pressed)
                console.ExecuteCommand($"callshuttle {_callShuttleTime.Text}");
            else
                console.ExecuteCommand($"callshuttlenorecall {_callShuttleTime.Text}");
        }
    }
}
