using Content.Shared._DV.Traits;
using Content.Shared._DV.Traits.Conditions;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._DV.Traits.UI;

[GenerateTypedNameReferences]
public sealed partial class TraitEntry : PanelContainer
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly ILocalizationManager _loc = default!;

    public event Action<bool>? OnToggled;

    public bool IsSelected => TraitCheckbox.Pressed;
    public int TraitCost { get; }

    private readonly TraitPrototype _trait;
    private bool _isUpdating;
    private readonly List<string> _failedConditionTooltips = new();

    public TraitEntry(TraitPrototype trait)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _trait = trait;
        TraitCost = trait.Cost;

        // Enable mouse events so tooltips work
        MouseFilter = MouseFilterMode.Pass;

        TraitNameLabel.Text = Loc.GetString(trait.Name);
        TraitDescriptionLabel.SetMessage(Loc.GetString(trait.Description));

        // Format cost display
        var costPrefix = trait.Cost > 0 ? "+" : "";
        var costColor = trait.Cost > 0 ? "#ff6b6b" : trait.Cost < 0 ? "#6bff6b" : "#888888";
        TraitCostLabel.Text = $"{costPrefix}{trait.Cost}";
        TraitCostLabel.ModulateSelfOverride = Color.FromHex(costColor);

        TraitCheckbox.OnToggled += OnCheckboxToggled;

        // Build condition tooltips
        UpdateConditionTooltips();
    }

    private void UpdateConditionTooltips()
    {
        var tooltips = new List<string>();

        foreach (var condition in _trait.Conditions)
        {
            var tooltip = condition.GetTooltip(_prototype, _loc);
            if (!string.IsNullOrEmpty(tooltip))
                tooltips.Add(tooltip);
        }

        if (tooltips.Count > 0)
        {
            var tooltipText = Loc.GetString("trait-conditions-tooltip",
                ("requirements", string.Join("\n", tooltips)));

            TooltipSupplier = _ => CreateMarkupTooltip(tooltipText);
        }
        else
            TooltipSupplier = null;
    }

    /// <summary>
    /// Creates a tooltip control that properly parses markup.
    /// </summary>
    private static Tooltip CreateMarkupTooltip(string markupText)
    {
        var tooltip = new Tooltip();

        // Parse the markup into a FormattedMessage
        tooltip.SetMessage(FormattedMessage.FromMarkupOrThrow(markupText));

        return tooltip;
    }

    /// <summary>
    /// Updates whether conditions are met based on current job/species.
    /// </summary>
    public void UpdateConditionsMet(string? jobId, string? speciesId)
    {
        _failedConditionTooltips.Clear();
        MeetsConditions = true;

        foreach (var condition in _trait.Conditions)
        {
            var result = condition switch
            {
                IsSpeciesCondition speciesCond => CheckSpeciesCondition(speciesCond, speciesId),
                HasJobCondition jobCond => CheckJobCondition(jobCond, jobId),
                InDepartmentCondition deptCond => CheckDepartmentCondition(deptCond, jobId),
                _ => true,
            };

            // Apply inversion
            result ^= condition.Invert;

            if (!result)
            {
                MeetsConditions = false;
                var tooltip = condition.GetTooltip(_prototype, _loc);
                if (!string.IsNullOrEmpty(tooltip))
                    _failedConditionTooltips.Add(tooltip);
            }
        }

        UpdateDisabledState();
    }

    private bool CheckSpeciesCondition(IsSpeciesCondition condition, string? speciesId)
    {
        if (string.IsNullOrEmpty(speciesId))
            return false;

        return speciesId == condition.Species.Id;
    }

    private bool CheckJobCondition(HasJobCondition condition, string? jobId)
    {
        if (string.IsNullOrEmpty(jobId))
            return false;

        return jobId == condition.Job;
    }

    private bool CheckDepartmentCondition(InDepartmentCondition condition, string? jobId)
    {
        if (string.IsNullOrEmpty(jobId))
            return false;

        if (!_prototype.TryIndex(condition.Department, out var department))
            return false;

        return department.Roles.Contains(jobId);
    }

    private void UpdateDisabledState()
    {
        TraitCheckbox.Disabled = !MeetsConditions;

        if (!MeetsConditions)
        {
            // Deselect if conditions no longer met
            if (TraitCheckbox.Pressed)
            {
                _isUpdating = true;
                TraitCheckbox.Pressed = false;
                UpdateSelectedStyle();
                _isUpdating = false;
                OnToggled?.Invoke(false);
            }

            // Show why it's disabled
            AddStyleClass("TraitsEntryDisabled");

            // Update tooltip to show failed conditions
            if (_failedConditionTooltips.Count > 0)
            {
                var tooltipText = Loc.GetString("trait-conditions-not-met-tooltip",
                    ("requirements", string.Join("\n", _failedConditionTooltips)));

                TooltipSupplier = _ => CreateMarkupTooltip(tooltipText);
            }
        }
        else
        {
            RemoveStyleClass("TraitsEntryDisabled");
            UpdateConditionTooltips(); // Reset to normal tooltips
        }
    }

    private void OnCheckboxToggled(BaseButton.ButtonToggledEventArgs args)
    {
        if (_isUpdating)
            return;

        if (!MeetsConditions)
        {
            // Prevent selection if conditions not met
            _isUpdating = true;
            TraitCheckbox.Pressed = false;
            _isUpdating = false;
            return;
        }

        UpdateSelectedStyle();
        OnToggled?.Invoke(args.Pressed);
    }

    public void SetSelected(bool selected)
    {
        _isUpdating = true;
        TraitCheckbox.Pressed = selected && MeetsConditions;
        UpdateSelectedStyle();
        _isUpdating = false;
    }

    public bool MeetsConditions { get; private set; } = true;

    private void UpdateSelectedStyle()
    {
        if (TraitCheckbox.Pressed)
            AddStyleClass("TraitsEntrySelected");
        else
            RemoveStyleClass("TraitsEntrySelected");
    }
}
