- type: entity
  name: arrest report
  parent: PaperTemplate
  id: PaperTemplateSecurityArrestReport
  description: 'Report why somebody was arrested'
  components:
  - type: Paper
    contentSize: 10000
    content: paperwork-security-arrest-report

- type: entity
  name: arrest warrant
  parent: PaperTemplate
  id: PaperTemplateSecurityArrestWarrant
  description: 'A warrant for someones arrest'
  components:
  - type: Paper
    contentSize: 10000
    content: paperwork-security-arrest-warrant

- type: entity
  name: department search warrant
  parent: PaperTemplate
  id: PaperTemplateSecurityDepartSearchWarrant
  description: 'A search warrant for an entire department.'
  components:
  - type: Paper
    contentSize: 10000
    content: paperwork-security-department-search-warrant

- type: entity
  name: detective report
  parent: PaperTemplate
  id: PaperTemplateSecurityDetectiveReport
  description: 'Reports the detectives findings'
  components:
  - type: Paper
    contentSize: 10000
    content: paperwork-security-detective-report

- type: entity
  name: furlough request
  parent: PaperTemplate
  id: PaperTemplateSecurityFurloughRequest
  description: 'Let an inmate walk free for a period of time'
  components:
  - type: Paper
    contentSize: 10000
    content: paperwork-security-furlough-request

- type: entity
  name: individual search warrant
  parent: PaperTemplate
  id: PaperTemplateSecurityIndividualSearchWarrant
  description: 'Search warrant for an individual'
  components:
  - type: Paper
    contentSize: 10000
    content: paperwork-security-individual-search-warrant

- type: entity
  name: inmate request
  parent: PaperTemplate
  id: PaperTemplateSecurityInmateRequest
  description: 'For an Inmate to request something.'
  components:
  - type: Paper
    contentSize: 10000
    content: paperwork-security-inmate-request

- type: entity
  name: visitation request
  parent: PaperTemplate
  id: PaperTemplateSecurityVisitationRequest
  description: 'Visit a prisoner for a period of time.'
  components:
  - type: Paper
    contentSize: 10000
    content: paperwork-security-visitation-request

- type: entity
  name: restricted equipment permit
  parent: PaperTemplate
  id: PaperTemplateSecurityRestrictedEquipmentPermit
  description: 'Those juicy jaws of life, sec will take it away if your missing this.'
  components:
  - type: Paper
    contentSize: 10000
    content: paperwork-security-restricted-equipment-permit


- type: entity
  name: restricted weapons permit
  parent: PaperTemplate
  id: PaperTemplateSecurityRestrictedWeaponsPermit
  description: 'A permit for restricted weapons.'
  components:
  - type: Paper
    contentSize: 10000
    content: paperwork-security-restricted-weapons-permit
