// SPDX-FileCopyrightText: 2025 Coenx-flex
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared._Mono.CorticalBorer;
using Content.Shared.Chemistry;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Mono.CorticalBorer;

[GenerateTypedNameReferences]
public sealed partial class CorticalBorerReagentCardControl : Control
{
    public Action<string>? OnPressed;

    public CorticalBorerReagentCardControl(CorticalBorerDispenserItem set)
    {
        RobustXamlLoader.Load(this);

        ColorPanel.PanelOverride = new StyleBoxFlat{ BackgroundColor = set.ReagentColor};
        ReagentNameLabel.Text = set.ReagentName;
        FillLabel.Text = Loc.GetString("cortical-borer-dispenser-window-cost", ("cost", set.Cost * set.Amount));

        // disable the button if you can't afford it, makes it easier
        MainButton.Disabled = set.Chems < set.Cost * set.Amount;

        MainButton.OnPressed += args => OnPressed?.Invoke(set.ReagentId);
    }
}

