- type: startingGear
  id: GhostBarNTPrisonerGear
  equipment:
    head: ClothingHeadHatOrangesoft
    jumpsuit: ClothingUniformJumpsuitPrisoner
    back: ClothingBackpackSatchel
    ears: ClothingHeadsetFreelance
    shoes: ClothingShoesColorBlack
    id: PrisonerPDA
    pocket1: FoodSnackEnergy
    pocket2: DrinkWaterBottleFull
