- type: startingGear
  id: GhostBarSyndicaWardenGear
  equipment:
    head: ClothingHeadHatSyndieMAA
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicate
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudSyndicate
    ears: ClothingHeadsetAltFreelancer
    neck: ClothingNeckCWPGorlex
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterVestWebElite
    shoes: ClothingShoesBootsCombatFilled
    id: SyndiPDA
    pocket1: WeaponDisabler
    pocket2: WeaponPistolViper
    belt: ClothingBeltMilitaryWebbingHostageWarden
