- type: department
  id: Justice
  name: department-Justice
  description: department-Justice-description
  color: "#701442"
  radioChannel: Justice
  roles:
  - ChiefJustice
  - Clerk
  - Prosecutor
  - Lawyer

- type: department
  id: Incarcerated
  name: department-Incarcerated
  description: department-Incarcerated-description
  radioChannel: Security # Notifies security on late-join
  color: "#3b3b3b"
  roles:
  - Prisoner
  - Gladiator
