- type: department
  id: Justice
  name: department-Justice
  description: department-Justice-description
  color: "#701442"
  radioChannel: Justice
  roles:
  - ChiefJustice
  - Clerk
  - Prosecutor
  - Lawyer
