- type: antag
  id: Conspirator
  name: roles-antag-conspirator-name
  antagonist: true
  setPreference: true
  objective: roles-antag-conspirator-objective
  guides: [ Conspirators ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 86400 # DeltaV - 24h

- type: antagSpecifier
  parent: RestrictedAntag
  id: Conspirator
  prefRoles:
  - Conspirator
  blacklist:
    components:
    - AntagImmune
  mindRoles:
  - MindRoleConspirator
  briefing:
    text: conspirator-role-greeting
    color: "#724F29"
    sound: /Audio/_Harmony/Misc/conspirator_greeting.ogg
  components:
  - type: Conspirator
  - type: AutoImplant
    implants:
    - RadioImplantConspiracy
